// Auto-generated athlete data from MASH Track Student Form 2026
// 53 athletes with PRs, injuries, goals, phone, emergency contacts

export const FORM_DATA = [
  {
    "n": "Lucy Ulrich",
    "g": 11,
    "gn": "F",
    "ph": "(715) 780-0545",
    "em": "Dustin Ulrich (715) 420-1417",
    "p1": "400",
    "p2": "Relay 4x200",
    "pr": "N/A",
    "inj": "No",
    "goal": "To do decent my first year",
    "imp": "400",
    "pg": "Consistency",
    "rv": "Discipline",
    "conf": "No",
    "sp": ""
  },
  {
    "n": "Sawyer Hoops",
    "g": 10,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "400",
    "p2": "200",
    "pr": "400 - around 52\n200 - 23.99",
    "inj": "No",
    "goal": "Consistent 50 sec 400",
    "imp": "400 and 200",
    "pg": "Consistency",
    "rv": "Discipline",
    "conf": "Wednesdays I work at 6 pm",
    "sp": "Football, basketball"
  },
  {
    "n": "Paxton",
    "g": 9,
    "gn": "M",
    "ph": "175 965 9514",
    "em": "Seth hamland 714 965 1244",
    "p1": "Disscuss",
    "p2": "Shot",
    "pr": "Idk",
    "inj": "None",
    "goal": "Throw good on discuss",
    "imp": "Discuss",
    "pg": "",
    "rv": "Resiliance",
    "conf": "No",
    "sp": "Football"
  },
  {
    "n": "Angus Hamland",
    "g": 10,
    "gn": "M",
    "ph": "715-964-7028",
    "em": "Seth Hamland 715-965-1244",
    "p1": "1600m",
    "p2": "800",
    "pr": "1600m 5:15 800m I forgot",
    "inj": "Nope",
    "goal": "Break 5 mins in the 1600m",
    "imp": "1600m",
    "pg": "Overall health",
    "rv": "D",
    "conf": "No",
    "sp": "Cross country Basketball Track"
  },
  {
    "n": "Xander Cynor",
    "g": 9,
    "gn": "M",
    "ph": "7153140987",
    "em": "Carl Cynor 715 964 4374",
    "p1": "Pole vault",
    "p2": "200",
    "pr": "Don't know",
    "inj": "None",
    "goal": "To get faster and more explosive",
    "imp": "Pole vault",
    "pg": "Getting to know teammates",
    "rv": "Attitude",
    "conf": "No",
    "sp": "Wrestling football"
  },
  {
    "n": "Colton Long",
    "g": 10,
    "gn": "M",
    "ph": "7159051279",
    "em": "Jeffery long 7159654008",
    "p1": "4x1",
    "p2": "100m",
    "pr": "100m 12.11 sec",
    "inj": "Left knee problems",
    "goal": "Under 12 secs",
    "imp": "100m",
    "pg": "Idk",
    "rv": "Discipline",
    "conf": "No",
    "sp": "Hockey and soccer"
  },
  {
    "n": "Willow Dassow",
    "g": 11,
    "gn": "F",
    "ph": "7159650699",
    "em": "Corey Dassow(715)965-5401",
    "p1": "800",
    "p2": "1600",
    "pr": "800m-2:43   1600m-6:13",
    "inj": "Femoral stress fracture during cross country",
    "goal": "Decrease times. 800m sub 2:30",
    "imp": "800",
    "pg": "To become a better leader",
    "rv": "Resilience and discipline",
    "conf": "No",
    "sp": "Cross country"
  },
  {
    "n": "Jonathan Bartnik",
    "g": 12,
    "gn": "M",
    "ph": "715-560-3312",
    "em": "Monica Bartnik 715-207-7869",
    "p1": "Shotput",
    "p2": "Discus",
    "pr": "33 shotput \n80 ish discus",
    "inj": "Recent shoulder surgery just cleared by doctor",
    "goal": "Throw farther",
    "imp": "Shotput",
    "pg": "Get in better shape",
    "rv": "Discipline",
    "conf": "Science Olympiad",
    "sp": ""
  },
  {
    "n": "Aliyah Pilgrim",
    "g": 12,
    "gn": "F",
    "ph": "7159658111",
    "em": "Melissa Pilgrim (715 965 6359)",
    "p1": "400",
    "p2": "200",
    "pr": "400- 1.03\n200-27",
    "inj": "none",
    "goal": "Work hard and get better while having fun",
    "imp": "400",
    "pg": "To be consistent everyday and have a good mindset towards practice everyday",
    "rv": "Resilience",
    "conf": "Yes, vacation (3/23-3/27)",
    "sp": "Volleyball, Basketball"
  },
  {
    "n": "Draven Dums",
    "g": 11,
    "gn": "M",
    "ph": "715-783-0298",
    "em": "Rena Dums 715-560-2538",
    "p1": "Long Jump",
    "p2": "Triple Jump",
    "pr": "N/A",
    "inj": "N/A",
    "goal": "To improve skills",
    "imp": "Long Jump",
    "pg": "Consistentcy",
    "rv": "Resilience",
    "conf": "Work, Band, Maybe Science Olympiad",
    "sp": "N/A"
  },
  {
    "n": "Isabella",
    "g": 10,
    "gn": "F",
    "ph": "7157532012",
    "em": "Tabitha Leischer- 9207162093",
    "p1": "Not sure, it\u2019s my first year",
    "p2": "",
    "pr": "",
    "inj": "I injured my knee freshman year, and it still affects me sometimes",
    "goal": "To become a better athlete",
    "imp": "My overall running ability",
    "pg": "",
    "rv": "Resilience",
    "conf": "I don\u2019t think so",
    "sp": "Cross country"
  },
  {
    "n": "Landon Preuss",
    "g": 9,
    "gn": "M",
    "ph": "715 965 6875",
    "em": "my mom...715 965 3415",
    "p1": "100m",
    "p2": "Na",
    "pr": "13 I think",
    "inj": "I don't think so",
    "goal": "Get a new pr",
    "imp": "100m",
    "pg": "Explosiveness",
    "rv": "Discipline",
    "conf": "I dont think so",
    "sp": "Soccer"
  },
  {
    "n": "Logan Langdon",
    "g": 11,
    "gn": "M",
    "ph": "7155605909",
    "em": "",
    "p1": "Discus",
    "p2": "Shotput",
    "pr": "125\" discus, 30's for shot",
    "inj": "Fractured sternum, months ago",
    "goal": "Personally improve",
    "imp": "Discus",
    "pg": "Display leadership in my event",
    "rv": "Respect",
    "conf": "No",
    "sp": "Football"
  },
  {
    "n": "Adalyn Dittrich",
    "g": 12,
    "gn": "F",
    "ph": "715.965.1833",
    "em": "OraLee Dittrich 715.965.4998",
    "p1": "Pole vault",
    "p2": "Hurdles",
    "pr": "N/a",
    "inj": "Knee injury",
    "goal": "Hopefully run and do pole vault since I have an injury right now",
    "imp": "Gain height in pole vault",
    "pg": "Consistency",
    "rv": "Resilience",
    "conf": "No",
    "sp": "Swim"
  },
  {
    "n": "Levi Zuleger",
    "g": 10,
    "gn": "M",
    "ph": "7159658832",
    "em": "Kathy Zuleger 715:5608398",
    "p1": "200 and 4-200",
    "p2": "100",
    "pr": "24.74 200m dash",
    "inj": "No",
    "goal": "23 in the 200m",
    "imp": "200m",
    "pg": "Leadership",
    "rv": "Attitude and resilience",
    "conf": "No",
    "sp": "Soccer and wrestling"
  },
  {
    "n": "Judah Wipf",
    "g": 10,
    "gn": "M",
    "ph": "7155602983",
    "em": "Korby Wipf 715-965-0592",
    "p1": "800",
    "p2": "Either 400 or 1600",
    "pr": "Open 8- 2:18 4x8 split 2:14",
    "inj": "Bee sting allergy",
    "goal": "Get some PRs",
    "imp": "800",
    "pg": "Have fun with friends",
    "rv": "Discipline",
    "conf": "I have club practice for soccer later in the season but it shouldn\u2019t interfere too much",
    "sp": "Soccer and basketball"
  },
  {
    "n": "Reuben Barnhart",
    "g": 12,
    "gn": "M",
    "ph": "518-414-1004",
    "em": "608-293-2270",
    "p1": "Shot put",
    "p2": "Discus",
    "pr": "",
    "inj": "No",
    "goal": "Have fun and succeed",
    "imp": "Shot put",
    "pg": "Consistency",
    "rv": "Discipline",
    "conf": "No",
    "sp": "Football"
  },
  {
    "n": "Luca Gumy",
    "g": 10,
    "gn": "M",
    "ph": "+1 (715) 560-0624",
    "em": "Sara Konieczny",
    "p1": "100",
    "p2": "Long jump",
    "pr": "Long jump: 5m 14cm\n80 meter sprint: 10.7 seconds",
    "inj": "Partly torn miniscus, not fully healed yet. And asthma",
    "goal": "To start with sports again after my injury",
    "imp": "My sprint",
    "pg": "Buy an aufi Rs 6 ABT legacy",
    "rv": "Discipline",
    "conf": "I dont think so",
    "sp": "Football"
  },
  {
    "n": "Evan Pagel",
    "g": 12,
    "gn": "M",
    "ph": "715-965-3266 (My #)",
    "em": "Hope Pagel 608-547-8556",
    "p1": "Mile",
    "p2": "800",
    "pr": "800: 2:18\nMile: 5:30\n2 mile: 11:40",
    "inj": "No",
    "goal": "Improve all my times and set new PRs",
    "imp": "Mile",
    "pg": "Consistency",
    "rv": "Integrity",
    "conf": "Youth expo May 15th",
    "sp": "Cross country"
  },
  {
    "n": "Axel",
    "g": 11,
    "gn": "M",
    "ph": "7155600451",
    "em": "7152161743",
    "p1": "Triple",
    "p2": "Sprints",
    "pr": "",
    "inj": "",
    "goal": "Become faster",
    "imp": "Sprints",
    "pg": "Leadership",
    "rv": "Integrity",
    "conf": "Working out",
    "sp": "Football"
  },
  {
    "n": "Luke Klapatauskas",
    "g": 10,
    "gn": "M",
    "ph": "7159650234",
    "em": "Karla",
    "p1": "Hurdles",
    "p2": "Triple jump",
    "pr": "43 seconds on 300 hurdles",
    "inj": "No no no",
    "goal": "State in 300 hurdles",
    "imp": "300 hurdles and relays",
    "pg": "Leadership and recruitment",
    "rv": "Resilience",
    "conf": "Yes i do training workouts 1-2 days a week at ETS in Eau Claire.  So i need to leave by 5:00/5:15.",
    "sp": "Football, Basketball"
  },
  {
    "n": "Cora Semrau",
    "g": 10,
    "gn": "F",
    "ph": "7159658472",
    "em": "Sara Semrau- 7159280400 Clint Semrau- 7169280799",
    "p1": "Hurdles both 100&300",
    "p2": "Relays- 4x1 or 4x2",
    "pr": "Unknown",
    "inj": "No",
    "goal": "To Pr",
    "imp": "300 hurdles",
    "pg": "Meet new people",
    "rv": "Empathy",
    "conf": "Some practices I may have to leave roughly 15 minutes early for work",
    "sp": "Tennis archery"
  },

  {
    "n": "Chloe Pipkorn",
    "g": 11,
    "gn": "F",
    "ph": "7159653484",
    "em": "Brandy",
    "p1": "",
    "p2": "",
    "pr": "",
    "inj": "Sublixation of the right knee, bursitis in right knee, patella tendencies in both knees, and swelling and strained both Achilles and asthma",
    "goal": "Try my best",
    "imp": "Long jump",
    "pg": "Confodence",
    "rv": "Attitude",
    "conf": "Not that I know off",
    "sp": "Hockey,swim,figure skating"
  },
  {
    "n": "Avery Losiewicz",
    "g": 11,
    "gn": "F",
    "ph": "715 965 6272",
    "em": "Katie Losiewicz 715 965 3111",
    "p1": "Pole Vault",
    "p2": "Hurdles",
    "pr": "I don't know them",
    "inj": "Yes I will be getting a cortisone shot in my hip on Wednesday March 11th.  I also have exercise induced asthma.",
    "goal": "Have a good time and beat my records from last year.",
    "imp": "Pole Vaulting",
    "pg": "Being a good role model and helping people who need it.",
    "rv": "Empathy",
    "conf": "Might have to leave early for wrestling practice.",
    "sp": "Wrestling, volleyball"
  },
  {
    "n": "Esmeralda Anderson",
    "g": 12,
    "gn": "F",
    "ph": "7152056873",
    "em": "Martha (715)651-6993",
    "p1": "800 or 1600",
    "p2": "Pole vault",
    "pr": "1600- 6.00",
    "inj": "Kidney infection as of right now. Should be gone by the end of spring break",
    "goal": "give all I can give, possibly get to varsity. Be consistent,",
    "imp": "Pole vault,",
    "pg": "To have fun, get the best I can out of the season, work as hard as I can.",
    "rv": "Sportsmanship, discipline,",
    "conf": "youth group",
    "sp": "Cross country"
  },
  {
    "n": "Avary Sigmund",
    "g": 9,
    "gn": "F",
    "ph": "7152149722",
    "em": "Dawn Sigmund. 715-965-4101",
    "p1": "Triple Jump",
    "p2": "200",
    "pr": "",
    "inj": "Yes, i have a torn labrum in my left shoulder currently",
    "goal": "To PR, get better and have fun",
    "imp": "Triple",
    "pg": "better attitude",
    "rv": "Resilience, attitude, and integrity",
    "conf": "i don\u2019t know",
    "sp": "Volleyball, wrestling"
  },
  {
    "n": "Cora Neitzel",
    "g": 9,
    "gn": "F",
    "ph": "715-965-3871",
    "em": "Meagan Neitzel 920-562-0100",
    "p1": "Discus",
    "p2": "Shot Put",
    "pr": "Idk",
    "inj": "Yes, I have a sprained ankle currently",
    "goal": "Get better and have fun",
    "imp": "Discus",
    "pg": "I want to make new friends and stay consistent",
    "rv": "Resilience",
    "conf": "I don\u2019t think so",
    "sp": "None"
  },
  {
    "n": "Melanie Richter",
    "g": 9,
    "gn": "F",
    "ph": "715-965-0896",
    "em": "Abra Richter 715-572-6196",
    "p1": "800",
    "p2": "1600",
    "pr": "800- 2:46 1600-5:59 3200- 13:20",
    "inj": "During cross country I had a stress fracture in my shin and was out for the season.",
    "goal": "Set new pr\u2019s and more specifically run a 2:35 800",
    "imp": "800",
    "pg": "To be a good teammate and supporter",
    "rv": "Resilience",
    "conf": "None",
    "sp": "Cross country and basketball"
  },
  {
    "n": "Savannah Hebert",
    "g": 9,
    "gn": "F",
    "ph": "7159659388",
    "em": "jessica rau 715-465-0550",
    "p1": "discus",
    "p2": "shot put",
    "pr": "shot put- around 23 discus- i forgot",
    "inj": "minor shoulder and hip from swim",
    "goal": "to better my self and get prs",
    "imp": "discus",
    "pg": "to be my best self",
    "rv": "discipline",
    "conf": "work. but i can just do saturdays",
    "sp": "swim"
  },
  {
    "n": "Parker Judnic",
    "g": 9,
    "gn": "M",
    "ph": "715-965-0217",
    "em": "Macie Judnic 715-965-3948",
    "p1": "Hurdles",
    "p2": "Relay",
    "pr": "27 seconds 200m hurdles,  about 48 seconds 4x400 relay",
    "inj": "No",
    "goal": "Get a good PR",
    "imp": "Hurdles",
    "pg": "Consistency",
    "rv": "Discipline",
    "conf": "No",
    "sp": "Soccer, Curling"
  },
  {
    "n": "Jordyn Grant",
    "g": 10,
    "gn": "F",
    "ph": "",
    "em": "Michele Grant, 715 - 560 - 0077",
    "p1": "triple jump",
    "p2": "sprinting, 100, 200",
    "pr": "triple jump - 32' 8.5\" 100 - 13.93 200 - 29.25",
    "inj": "",
    "goal": "get faster and get 34 feet in triple jump, go to state",
    "imp": "triple jump, sprinting",
    "pg": "",
    "rv": "Discipline",
    "conf": "no",
    "sp": "gymnastics"
  },
  {
    "n": "Logan Schmidt",
    "g": 9,
    "gn": "M",
    "ph": "715 314 1886",
    "em": "Wensy Ness, 920 858 4099",
    "p1": "Diskus",
    "p2": "Shotput",
    "pr": "Diskus ~75 ft Shot ~26 ft",
    "inj": "No",
    "goal": "PR is my events",
    "imp": "Diskus",
    "pg": "To make myself better everyday and break some of my own records.",
    "rv": "Resilience",
    "conf": "No",
    "sp": "Soccer and archery"
  },
  {
    "n": "Sada Carstensen",
    "g": 9,
    "gn": "F",
    "ph": "Sada Carstensen 715-955-0514",
    "em": "Tara Thompson 715-965-6650",
    "p1": "Shot Put",
    "p2": "Discus",
    "pr": "Shot Put: around 27.5\u201d Discus: around 91.6\u201d",
    "inj": "My knee was injured in January still gives me some problems here and there, diagnosed with runners/ jumpers knee as it is known as.",
    "goal": "Throw better and improve from last year and place decently",
    "imp": "Shot Put",
    "pg": "Be a leader on the field and staying coachable",
    "rv": "",
    "conf": "Dance as I explained above.",
    "sp": "Volleyball, dance"
  },
  {
    "n": "Mya Matthias",
    "g": 11,
    "gn": "F",
    "ph": "7159652340",
    "em": "Shelly Matthias",
    "p1": "",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "Learn new things and try a new sport.",
    "imp": "Both of them",
    "pg": "Stay consistent with school and keep my grades up.",
    "rv": "Resilience",
    "conf": "No",
    "sp": "N/A"
  },
  {
    "n": "Autumn Cooley",
    "g": 12,
    "gn": "F",
    "ph": "715-560-5316",
    "em": "Jenny R 715-560-3132",
    "p1": "4x800",
    "p2": "4x4",
    "pr": "(800) 2:38 \n(400) 1:07\n(200) :25",
    "inj": "Torn hip labrum",
    "goal": "Make it back to sectionals in 4x8",
    "imp": "4x8",
    "pg": "Keep running through the pain till my limit",
    "rv": "Respect. Attitude",
    "conf": "No",
    "sp": "Tennis"
  },
  {
    "n": "Naomi Thomas",
    "g": 10,
    "gn": "F",
    "ph": "7159657715",
    "em": "Mindy Thomas 7159652377",
    "p1": "Shot put",
    "p2": "discus",
    "pr": "",
    "inj": "no",
    "goal": "throw farther and get stronger",
    "imp": "shot put",
    "pg": "Consistency",
    "rv": "Resilience",
    "conf": "no",
    "sp": "none"
  },
  {
    "n": "Lindsay Kahn",
    "g": 12,
    "gn": "F",
    "ph": "715-314-0219",
    "em": "Mary Kahn 507-421-7216",
    "p1": "1600meter",
    "p2": "800meter",
    "pr": "3200 meter- 12:28\n1600 meter- 5:39\n800 meter- 2:31",
    "inj": "No",
    "goal": "Make it to State in either 3 of my events. Get PRs in all 3 events this year.",
    "imp": "1600m",
    "pg": "I want to take a leader role this year for the group.",
    "rv": "Resilience",
    "conf": "Not that I know of.",
    "sp": "Cross Country"
  },
  {
    "n": "Alexis Zuleger",
    "g": 12,
    "gn": "F",
    "ph": "(715)560-8397",
    "em": "John Zuleger",
    "p1": "200, 200 rely",
    "p2": "4x400",
    "pr": "Idk",
    "inj": "Pulled my calf muscle but not bad",
    "goal": "Run the best I can",
    "imp": "200 or 400",
    "pg": "Be positive",
    "rv": "Attitude",
    "conf": "No",
    "sp": "None"
  },
  {
    "n": "Raylin Rothmeier",
    "g": 10,
    "gn": "F",
    "ph": "7159659879",
    "em": "Lindsay Campbell 715-965-0156",
    "p1": "Triple jump",
    "p2": "400",
    "pr": "N/A",
    "inj": "No",
    "goal": "To improve and break personal records as the season continues",
    "imp": "Triple jump",
    "pg": "I would like to show leadership and determination",
    "rv": "Discipline",
    "conf": "I will have a few practices I have to miss due to having gymnastics practice in Marshfield.",
    "sp": "Tennis, gymnastics"
  },
  {
    "n": "Tristan Newberry",
    "g": 10,
    "gn": "M",
    "ph": "715 574 5973",
    "em": "Rachel Newberry (608) 518-8753",
    "p1": "Long jump",
    "p2": "100",
    "pr": "N/A",
    "inj": "N/A",
    "goal": "To try my hardest at something new",
    "imp": "Long jump",
    "pg": "Leadership",
    "rv": "Discipline",
    "conf": "Nope",
    "sp": "N/A"
  },
  {
    "n": "Jordan Lavin",
    "g": 11,
    "gn": "M",
    "ph": "715-960-8576",
    "em": "Liz nuernburger 715-560-1399",
    "p1": "Pole vault",
    "p2": "N/A",
    "pr": "12ft",
    "inj": "N/A",
    "goal": "To jump 14ft or higher and win state",
    "imp": "Pole vault",
    "pg": "To push my teammates",
    "rv": "Sportsmanship",
    "conf": "No",
    "sp": "Cross country"
  },
  {
    "n": "Eric Paul",
    "g": 10,
    "gn": "M",
    "ph": "715-965-5094",
    "em": "Lynn Paul\u2014715-965-8354",
    "p1": "100m",
    "p2": "Triple Jump",
    "pr": "No clue",
    "inj": "No",
    "goal": "Get faster and jump farther",
    "imp": "Triple jump",
    "pg": "Consistency",
    "rv": "Sportsmanship",
    "conf": "No",
    "sp": "Soccer, archery"
  },
  {
    "n": "Nevyn Gripentrog",
    "g": 11,
    "gn": "M",
    "ph": "7158973190",
    "em": "Nicole Gripentrog 7158973189",
    "p1": "800",
    "p2": "1600",
    "pr": "I don't know",
    "inj": "No",
    "goal": "Improve from laat year",
    "imp": "800",
    "pg": "Consistency",
    "rv": "Resilience",
    "conf": "No",
    "sp": "Cross Country"
  },
  {
    "n": "Will Daniels",
    "g": 12,
    "gn": "M",
    "ph": "7156796798",
    "em": "Ray Daniels 715-560-2506",
    "p1": "300m Hurdles",
    "p2": "110m Hurdles",
    "pr": "40.3 -300m hurdles.   15.8 -110m hurdles",
    "inj": "ankle tweak",
    "goal": "podium at state",
    "imp": "300m Hurdles",
    "pg": "Be a great teammate",
    "rv": "Discipline",
    "conf": "Yes, wednesdays coaching aau",
    "sp": "Basketball, XC"
  },
  {
    "n": "Ryker Hallam",
    "g": 12,
    "gn": "M",
    "ph": "715-314-9042",
    "em": "Elizabeth Hallam 715-314-2048",
    "p1": "200 Relay",
    "p2": "Long Jump",
    "pr": "",
    "inj": "No",
    "goal": "To get 1st place",
    "imp": "To Jump farther on the long Jump",
    "pg": "To do my best",
    "rv": "Discipline",
    "conf": "Not that I know of",
    "sp": "Basketball"
  },
  {
    "n": "Rivalee Stokes",
    "g": 12,
    "gn": "F",
    "ph": "7159655923",
    "em": "Katie stokes 7155701872",
    "p1": "Discus",
    "p2": "100",
    "pr": "",
    "inj": "No",
    "goal": "Go to state",
    "imp": "Discus",
    "pg": "Be the best I can I can be",
    "rv": "",
    "conf": "",
    "sp": "Hockey"
  },
  {
    "n": "Ethan Jacobsen",
    "g": 10,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "High Jump",
    "p2": "Hurdles",
    "pr": "",
    "inj": "No",
    "goal": "Improve in all events",
    "imp": "High Jump",
    "pg": "Consistency",
    "rv": "Discipline",
    "conf": "No",
    "sp": ""
  },
  {
    "n": "Jasper Stokes",
    "g": 10,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Triple Jump",
    "p2": "High Jump",
    "pr": "TJ 37-5.5 HJ 5-0 LJ 18-0",
    "inj": "No",
    "goal": "State qualifier in triple jump",
    "imp": "Triple Jump",
    "pg": "Leadership",
    "rv": "Discipline",
    "conf": "No",
    "sp": ""
  },
  {
    "n": "Jovenski Macrsaint-Vil",
    "g": 9,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Blake Thoreson",
    "g": 11,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Throws",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Taylor Klingbeil",
    "g": 11,
    "gn": "F",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Chelsea Dick",
    "g": 10,
    "gn": "F",
    "ph": "",
    "em": "",
    "p1": "",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Alessia Salamin",
    "g": 10,
    "gn": "F",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Ellie Eckert",
    "g": 11,
    "gn": "F",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Mariah Salzer",
    "g": 9,
    "gn": "F",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Drayton Britz",
    "g": 9,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Max Losiewicz",
    "g": 9,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Pole Vault",
    "p2": "",
    "pr": "9-6",
    "inj": "",
    "goal": "",
    "imp": "Pole Vault",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Tosh Satterwhite",
    "g": 9,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Christopher Dunn",
    "g": 11,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Parker Fogo",
    "g": 11,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Throws",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Alan Scheel",
    "g": 11,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Jaden Thao",
    "g": 10,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Emmanuel Espinoza",
    "g": 10,
    "gn": "M",
    "ph": "7155743258",
    "em": "Dad 715-409-9913",
    "p1": "100 meter dash",
    "p2": "800 meter run relay",
    "pr": "",
    "inj": "No",
    "goal": "To improve my running and make it to varsity",
    "imp": "200 meter dash",
    "pg": "Consistency",
    "rv": "Resilience",
    "conf": "No",
    "sp": "Cross country, basketball"
  },
];

export const MEETS = [
  {id:1,date:"2026-03-24",name:"Marshfield Boys Indoor",loc:"Marshfield",g:"B",type:"away",bus:"2:30 PM",start:"4:30 PM",deadline:"ASAP",hl:true},
  {id:2,date:"2026-03-26",name:"Marshfield Girls Indoor",loc:"Marshfield",g:"G",type:"away",bus:"2:30 PM",start:"4:45 PM",deadline:"Wed 3/25 @ 5PM",hl:true},
  {id:3,date:"2026-03-27",name:"Northern Badger Classic",loc:"UW-Stout",g:"B/G",type:"away",bus:"12:30 PM",start:"3:00 PM",deadline:"Wed 3/25 @ NOON"},
  {id:4,date:"2026-04-02",name:"Stout Elite Meet",loc:"UW-Stout",g:"B/G",type:"away",bus:"12:30 PM",start:"3:00 PM",deadline:"Sun 3/29 @ midnight"},
  {id:5,date:"2026-04-04",name:"UWSP Distance Carnival",loc:"Stevens Point",g:"B/G",type:"away",start:"2:00 PM",deadline:"Thu 4/2 @ 8PM"},
  {id:6,date:"2026-04-09",name:"Medford Home Invite",loc:"Medford",g:"B/G",type:"home",start:"4:00 PM"},
  {id:7,date:"2026-04-14",name:"Stratford Invitational",loc:"Stratford",g:"B/G",type:"away",bus:"2:15 PM",start:"4:00 PM"},
  {id:8,date:"2026-04-23",name:"Medford Home Invite #2",loc:"Medford",g:"B/G",type:"home",start:"4:00 PM"},
  {id:9,date:"2026-05-01",name:"Spencer Invitational",loc:"Spencer",g:"B/G",type:"away",bus:"2:30 PM",start:"4:15 PM"},
  {id:10,date:"2026-05-05",name:"Lakeland Meet",loc:"Lakeland",g:"B/G",type:"away",bus:"1:15 PM",start:"4:00 PM"},
  {id:11,date:"2026-05-08",name:"Merrill Invitational",loc:"Merrill",g:"B/G",type:"away",start:"5:00 PM"},
  {id:12,date:"2026-05-12",name:"Marathon Meet",loc:"Marathon",g:"B/G",type:"away",bus:"2:30 PM",start:"4:30 PM"},
  {id:13,date:"2026-05-15",name:"Marshfield Invitational",loc:"Marshfield",g:"B/G",type:"away",bus:"2:00 PM",start:"4:00 PM"},
  {id:14,date:"2026-05-19",name:"GNC Conference",loc:"Rhinelander",g:"B/G",type:"conf",bus:"1:15 PM",start:"4:00 PM"},
  {id:15,date:"2026-05-26",name:"WIAA Regional",loc:"Medford",g:"B/G",type:"regional",start:"4:00 PM"},
  {id:16,date:"2026-05-29",name:"WIAA Sectional",loc:"Rice Lake",g:"B/G",type:"sectional",bus:"1:00 PM",start:"4:00 PM"},
];

export const LOCATIONS = {
  "Medford":{lat:45.1386,lon:-90.3412,zip:"54451"},
  "Marshfield":{lat:44.6688,lon:-90.1718},
  "UW-Stout":{lat:44.8755,lon:-91.9193},
  "Stevens Point":{lat:44.5236,lon:-89.5746},
  "Stratford":{lat:44.8017,lon:-90.0787},
  "Spencer":{lat:44.7563,lon:-90.2970},
  "Lakeland":{lat:45.8911,lon:-89.2451},
  "Merrill":{lat:45.1810,lon:-89.6832},
  "Marathon":{lat:44.9275,lon:-89.8401},
  "Rhinelander":{lat:45.6366,lon:-89.4121},
  "Rice Lake":{lat:45.5060,lon:-91.7382},
};

export const ACTIONS = [
  {id:1,t:"\u26A0\uFE0F PV weigh-ins Mon 3/23",d:"2026-03-23",p:"h"},
  {id:2,t:"\uD83D\uDCCB Enter Marshfield BOYS (wi.milesplit.com)",d:"2026-03-23",p:"h"},
  {id:3,t:"\uD83D\uDCCB Enter Marshfield GIRLS (deadline Wed 5PM)",d:"2026-03-25",p:"h"},
  {id:4,t:"\uD83D\uDCCB Northern Badger (deadline Wed NOON, pttiming.com)",d:"2026-03-25",p:"h"},
  {id:5,t:"\uD83D\uDCB0 NB payment via Athletic.net",d:"2026-03-25",p:"m"},
  {id:6,t:"\uD83D\uDCCB Stout Elite (deadline Sun midnight)",d:"2026-03-29",p:"m"},
  {id:7,t:"\uD83D\uDCCB UWSP Distance Carnival (deadline 4/2 8PM) + contract",d:"2026-04-02",p:"m"},
  {id:8,t:"\uD83C\uDFCB\uFE0F Confirm split-meet coaching",d:"2026-03-23",p:"h"},
];

export const KNOWN_STATUS = {
  "Evan Pagel":"limited",
  "Sawyer Hoops":"modified",
  "Colton Long":"modified",
  "Autumn Cooley":"limited",
  "Aliyah Pilgrim":"unavailable",
  "Avery Losiewicz":"injured",
  "Rivalee Stokes":"limited",
};
