// Auto-generated athlete data from MASH Track Student Form 2026
// 53 athletes with PRs, injuries, goals, phone, emergency contacts

export const FORM_DATA = [
  {
    "n": "Lucy Ulrich",
    "g": 11,
    "gn": "F",
    "ph": "(715) 780-0545",
    "em": "Dustin Ulrich (715) 420-1417",
    "p1": "400",
    "p2": "Relay 4x200",
    "pr": "N/A",
    "inj": "No",
    "goal": "To do decent my first year",
    "imp": "400",
    "pg": "Consistency",
    "rv": "Discipline",
    "conf": "No",
    "sp": ""
  },
  {
    "n": "Sawyer Hoops",
    "g": 10,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "400",
    "p2": "200",
    "pr": "400 - around 52\n200 - 23.99",
    "inj": "No",
    "goal": "Consistent 50 sec 400",
    "imp": "400 and 200",
    "pg": "Consistency",
    "rv": "Discipline",
    "conf": "Wednesdays I work at 6 pm",
    "sp": "Football, basketball"
  },
  {
    "n": "Paxton",
    "g": 9,
    "gn": "M",
    "ph": "175 965 9514",
    "em": "Seth hamland 714 965 1244",
    "p1": "Disscuss",
    "p2": "Shot",
    "pr": "Idk",
    "inj": "None",
    "goal": "Throw good on discuss",
    "imp": "Discuss",
    "pg": "",
    "rv": "Resiliance",
    "conf": "No",
    "sp": "Football"
  },
  {
    "n": "Angus Hamland",
    "g": 10,
    "gn": "M",
    "ph": "715-964-7028",
    "em": "Seth Hamland 715-965-1244",
    "p1": "1600m",
    "p2": "800",
    "pr": "1600m 5:15 800m I forgot",
    "inj": "Nope",
    "goal": "Break 5 mins in the 1600m",
    "imp": "1600m",
    "pg": "Overall health",
    "rv": "D",
    "conf": "No",
    "sp": "Cross country Basketball Track"
  },
  {
    "n": "Xander Cynor",
    "g": 9,
    "gn": "M",
    "ph": "7153140987",
    "em": "Carl Cynor 715 964 4374",
    "p1": "Pole vault",
    "p2": "200",
    "pr": "Don't know",
    "inj": "None",
    "goal": "To get faster and more explosive",
    "imp": "Pole vault",
    "pg": "Getting to know teammates",
    "rv": "Attitude",
    "conf": "No",
    "sp": "Wrestling football"
  },
  {
    "n": "Colton Long",
    "g": 10,
    "gn": "M",
    "ph": "7159051279",
    "em": "Jeffery long 7159654008",
    "p1": "4x1",
    "p2": "100m",
    "pr": "100m 12.11 sec",
    "inj": "Left knee problems",
    "goal": "Under 12 secs",
    "imp": "100m",
    "pg": "Idk",
    "rv": "Discipline",
    "conf": "No",
    "sp": "Hockey and soccer"
  },
  {
    "n": "Willow Dassow",
    "g": 11,
    "gn": "F",
    "ph": "7159650699",
    "em": "Corey Dassow(715)965-5401",
    "p1": "800",
    "p2": "1600",
    "pr": "800m-2:43   1600m-6:13",
    "inj": "Femoral stress fracture during cross country",
    "goal": "Decrease times. 800m sub 2:30",
    "imp": "800",
    "pg": "To become a better leader",
    "rv": "Resilience and discipline",
    "conf": "No",
    "sp": "Cross country"
  },
  {
    "n": "Jonathan Bartnik",
    "g": 12,
    "gn": "M",
    "ph": "715-560-3312",
    "em": "Monica Bartnik 715-207-7869",
    "p1": "Shotput",
    "p2": "Discus",
    "pr": "33 shotput \n80 ish discus",
    "inj": "Recent shoulder surgery just cleared by doctor",
    "goal": "Throw farther",
    "imp": "Shotput",
    "pg": "Get in better shape",
    "rv": "Discipline",
    "conf": "Science Olympiad",
    "sp": ""
  },
  {
    "n": "Aliyah Pilgrim",
    "g": 12,
    "gn": "F",
    "ph": "7159658111",
    "em": "Melissa Pilgrim (715 965 6359)",
    "p1": "400",
    "p2": "200",
    "pr": "400- 1.03\n200-27",
    "inj": "none",
    "goal": "Work hard and get better while having fun",
    "imp": "400",
    "pg": "To be consistent everyday and have a good mindset towards practice everyday",
    "rv": "Resilience",
    "conf": "Yes, vacation (3/23-3/27)",
    "sp": "Volleyball, Basketball"
  },
  {
    "n": "Draven Dums",
    "g": 11,
    "gn": "M",
    "ph": "715-783-0298",
    "em": "Rena Dums 715-560-2538",
    "p1": "Long Jump",
    "p2": "Triple Jump",
    "pr": "N/A",
    "inj": "N/A",
    "goal": "To improve skills",
    "imp": "Long Jump",
    "pg": "Consistentcy",
    "rv": "Resilience",
    "conf": "Work, Band, Maybe Science Olympiad",
    "sp": "N/A"
  },
  {
    "n": "Isabella",
    "g": 10,
    "gn": "F",
    "ph": "7157532012",
    "em": "Tabitha Leischer- 9207162093",
    "p1": "Not sure, it\u2019s my first year",
    "p2": "",
    "pr": "",
    "inj": "I injured my knee freshman year, and it still affects me sometimes",
    "goal": "To become a better athlete",
    "imp": "My overall running ability",
    "pg": "",
    "rv": "Resilience",
    "conf": "I don\u2019t think so",
    "sp": "Cross country"
  },
  {
    "n": "Landon Preuss",
    "g": 9,
    "gn": "M",
    "ph": "715 965 6875",
    "em": "my mom...715 965 3415",
    "p1": "100m",
    "p2": "Na",
    "pr": "13 I think",
    "inj": "I don't think so",
    "goal": "Get a new pr",
    "imp": "100m",
    "pg": "Explosiveness",
    "rv": "Discipline",
    "conf": "I dont think so",
    "sp": "Soccer"
  },
  {
    "n": "Logan Langdon",
    "g": 11,
    "gn": "M",
    "ph": "7155605909",
    "em": "",
    "p1": "Discus",
    "p2": "Shotput",
    "pr": "125\" discus, 30's for shot",
    "inj": "Fractured sternum, months ago",
    "goal": "Personally improve",
    "imp": "Discus",
    "pg": "Display leadership in my event",
    "rv": "Respect",
    "conf": "No",
    "sp": "Football"
  },
  {
    "n": "Adalyn Dittrich",
    "g": 12,
    "gn": "F",
    "ph": "715.965.1833",
    "em": "OraLee Dittrich 715.965.4998",
    "p1": "Pole vault",
    "p2": "Hurdles",
    "pr": "N/a",
    "inj": "Knee injury",
    "goal": "Hopefully run and do pole vault since I have an injury right now",
    "imp": "Gain height in pole vault",
    "pg": "Consistency",
    "rv": "Resilience",
    "conf": "No",
    "sp": "Swim"
  },
  {
    "n": "Levi Zuleger",
    "g": 10,
    "gn": "M",
    "ph": "7159658832",
    "em": "Kathy Zuleger 715:5608398",
    "p1": "200 and 4-200",
    "p2": "100",
    "pr": "24.74 200m dash",
    "inj": "No",
    "goal": "23 in the 200m",
    "imp": "200m",
    "pg": "Leadership",
    "rv": "Attitude and resilience",
    "conf": "No",
    "sp": "Soccer and wrestling"
  },
  {
    "n": "Judah Wipf",
    "g": 10,
    "gn": "M",
    "ph": "7155602983",
    "em": "Korby Wipf 715-965-0592",
    "p1": "800",
    "p2": "Either 400 or 1600",
    "pr": "Open 8- 2:18 4x8 split 2:14",
    "inj": "Bee sting allergy",
    "goal": "Get some PRs",
    "imp": "800",
    "pg": "Have fun with friends",
    "rv": "Discipline",
    "conf": "I have club practice for soccer later in the season but it shouldn\u2019t interfere too much",
    "sp": "Soccer and basketball"
  },
  {
    "n": "Reuben Barnhart",
    "g": 12,
    "gn": "M",
    "ph": "518-414-1004",
    "em": "608-293-2270",
    "p1": "Shot put",
    "p2": "Discus",
    "pr": "",
    "inj": "No",
    "goal": "Have fun and succeed",
    "imp": "Shot put",
    "pg": "Consistency",
    "rv": "Discipline",
    "conf": "No",
    "sp": "Football"
  },
  {
    "n": "Luca Gumy",
    "g": 10,
    "gn": "M",
    "ph": "+1 (715) 560-0624",
    "em": "Sara Konieczny",
    "p1": "100",
    "p2": "Long jump",
    "pr": "Long jump: 5m 14cm\n80 meter sprint: 10.7 seconds",
    "inj": "Partly torn miniscus, not fully healed yet. And asthma",
    "goal": "To start with sports again after my injury",
    "imp": "My sprint",
    "pg": "Buy an aufi Rs 6 ABT legacy",
    "rv": "Discipline",
    "conf": "I dont think so",
    "sp": "Football"
  },
  {
    "n": "Evan Pagel",
    "g": 12,
    "gn": "M",
    "ph": "715-965-3266 (My #)",
    "em": "Hope Pagel 608-547-8556",
    "p1": "Mile",
    "p2": "800",
    "pr": "800: 2:18\nMile: 5:30\n2 mile: 11:40",
    "inj": "No",
    "goal": "Improve all my times and set new PRs",
    "imp": "Mile",
    "pg": "Consistency",
    "rv": "Integrity",
    "conf": "Youth expo May 15th",
    "sp": "Cross country"
  },
  {
    "n": "Axel",
    "g": 11,
    "gn": "M",
    "ph": "7155600451",
    "em": "7152161743",
    "p1": "Triple",
    "p2": "Sprints",
    "pr": "",
    "inj": "",
    "goal": "Become faster",
    "imp": "Sprints",
    "pg": "Leadership",
    "rv": "Integrity",
    "conf": "Working out",
    "sp": "Football"
  },
  {
    "n": "Luke Klapatauskas",
    "g": 10,
    "gn": "M",
    "ph": "7159650234",
    "em": "Karla",
    "p1": "Hurdles",
    "p2": "Triple jump",
    "pr": "43 seconds on 300 hurdles",
    "inj": "No no no",
    "goal": "State in 300 hurdles",
    "imp": "300 hurdles and relays",
    "pg": "Leadership and recruitment",
    "rv": "Resilience",
    "conf": "Yes i do training workouts 1-2 days a week at ETS in Eau Claire.  So i need to leave by 5:00/5:15.",
    "sp": "Football, Basketball"
  },
  {
    "n": "Cora Semrau",
    "g": 10,
    "gn": "F",
    "ph": "7159658472",
    "em": "Sara Semrau- 7159280400 Clint Semrau- 7169280799",
    "p1": "Hurdles both 100&300",
    "p2": "Relays- 4x1 or 4x2",
    "pr": "Unknown",
    "inj": "No",
    "goal": "To Pr",
    "imp": "300 hurdles",
    "pg": "Meet new people",
    "rv": "Empathy",
    "conf": "Some practices I may have to leave roughly 15 minutes early for work",
    "sp": "Tennis archery"
  },

  {
    "n": "Chloe Pipkorn",
    "g": 11,
    "gn": "F",
    "ph": "7159653484",
    "em": "Brandy",
    "p1": "",
    "p2": "",
    "pr": "",
    "inj": "Sublixation of the right knee, bursitis in right knee, patella tendencies in both knees, and swelling and strained both Achilles and asthma",
    "goal": "Try my best",
    "imp": "Long jump",
    "pg": "Confodence",
    "rv": "Attitude",
    "conf": "Not that I know off",
    "sp": "Hockey,swim,figure skating"
  },
  {
    "n": "Avery Losiewicz",
    "g": 11,
    "gn": "F",
    "ph": "715 965 6272",
    "em": "Katie Losiewicz 715 965 3111",
    "p1": "Pole Vault",
    "p2": "Hurdles",
    "pr": "I don't know them",
    "inj": "Yes I will be getting a cortisone shot in my hip on Wednesday March 11th.  I also have exercise induced asthma.",
    "goal": "Have a good time and beat my records from last year.",
    "imp": "Pole Vaulting",
    "pg": "Being a good role model and helping people who need it.",
    "rv": "Empathy",
    "conf": "Might have to leave early for wrestling practice.",
    "sp": "Wrestling, volleyball"
  },
  {
    "n": "Esmeralda Anderson",
    "g": 12,
    "gn": "F",
    "ph": "7152056873",
    "em": "Martha (715)651-6993",
    "p1": "800 or 1600",
    "p2": "Pole vault",
    "pr": "1600- 6.00",
    "inj": "Kidney infection as of right now. Should be gone by the end of spring break",
    "goal": "give all I can give, possibly get to varsity. Be consistent,",
    "imp": "Pole vault,",
    "pg": "To have fun, get the best I can out of the season, work as hard as I can.",
    "rv": "Sportsmanship, discipline,",
    "conf": "youth group",
    "sp": "Cross country"
  },
  {
    "n": "Avary Sigmund",
    "g": 9,
    "gn": "F",
    "ph": "7152149722",
    "em": "Dawn Sigmund. 715-965-4101",
    "p1": "Triple Jump",
    "p2": "200",
    "pr": "",
    "inj": "Yes, i have a torn labrum in my left shoulder currently",
    "goal": "To PR, get better and have fun",
    "imp": "Triple",
    "pg": "better attitude",
    "rv": "Resilience, attitude, and integrity",
    "conf": "i don\u2019t know",
    "sp": "Volleyball, wrestling"
  },
  {
    "n": "Cora Neitzel",
    "g": 9,
    "gn": "F",
    "ph": "715-965-3871",
    "em": "Meagan Neitzel 920-562-0100",
    "p1": "Discus",
    "p2": "Shot Put",
    "pr": "Idk",
    "inj": "Yes, I have a sprained ankle currently",
    "goal": "Get better and have fun",
    "imp": "Discus",
    "pg": "I want to make new friends and stay consistent",
    "rv": "Resilience",
    "conf": "I don\u2019t think so",
    "sp": "None"
  },
  {
    "n": "Melanie Richter",
    "g": 9,
    "gn": "F",
    "ph": "715-965-0896",
    "em": "Abra Richter 715-572-6196",
    "p1": "800",
    "p2": "1600",
    "pr": "800- 2:46 1600-5:59 3200- 13:20",
    "inj": "During cross country I had a stress fracture in my shin and was out for the season.",
    "goal": "Set new pr\u2019s and more specifically run a 2:35 800",
    "imp": "800",
    "pg": "To be a good teammate and supporter",
    "rv": "Resilience",
    "conf": "None",
    "sp": "Cross country and basketball"
  },
  {
    "n": "Savannah Hebert",
    "g": 9,
    "gn": "F",
    "ph": "7159659388",
    "em": "jessica rau 715-465-0550",
    "p1": "discus",
    "p2": "shot put",
    "pr": "shot put- around 23 discus- i forgot",
    "inj": "minor shoulder and hip from swim",
    "goal": "to better my self and get prs",
    "imp": "discus",
    "pg": "to be my best self",
    "rv": "discipline",
    "conf": "work. but i can just do saturdays",
    "sp": "swim"
  },
  {
    "n": "Parker Judnic",
    "g": 9,
    "gn": "M",
    "ph": "715-965-0217",
    "em": "Macie Judnic 715-965-3948",
    "p1": "Hurdles",
    "p2": "Relay",
    "pr": "27 seconds 200m hurdles,  about 48 seconds 4x400 relay",
    "inj": "No",
    "goal": "Get a good PR",
    "imp": "Hurdles",
    "pg": "Consistency",
    "rv": "Discipline",
    "conf": "No",
    "sp": "Soccer, Curling"
  },
  {
    "n": "Jordyn Grant",
    "g": 10,
    "gn": "F",
    "ph": "",
    "em": "Michele Grant, 715 - 560 - 0077",
    "p1": "triple jump",
    "p2": "sprinting, 100, 200",
    "pr": "triple jump - 32' 8.5\" 100 - 13.93 200 - 29.25",
    "inj": "",
    "goal": "get faster and get 34 feet in triple jump, go to state",
    "imp": "triple jump, sprinting",
    "pg": "",
    "rv": "Discipline",
    "conf": "no",
    "sp": "gymnastics"
  },
  {
    "n": "Logan Schmidt",
    "g": 9,
    "gn": "M",
    "ph": "715 314 1886",
    "em": "Wensy Ness, 920 858 4099",
    "p1": "Diskus",
    "p2": "Shotput",
    "pr": "Diskus ~75 ft Shot ~26 ft",
    "inj": "No",
    "goal": "PR is my events",
    "imp": "Diskus",
    "pg": "To make myself better everyday and break some of my own records.",
    "rv": "Resilience",
    "conf": "No",
    "sp": "Soccer and archery"
  },
  {
    "n": "Sada Carstensen",
    "g": 9,
    "gn": "F",
    "ph": "Sada Carstensen 715-955-0514",
    "em": "Tara Thompson 715-965-6650",
    "p1": "Shot Put",
    "p2": "Discus",
    "pr": "Shot Put: around 27.5\u201d Discus: around 91.6\u201d",
    "inj": "My knee was injured in January still gives me some problems here and there, diagnosed with runners/ jumpers knee as it is known as.",
    "goal": "Throw better and improve from last year and place decently",
    "imp": "Shot Put",
    "pg": "Be a leader on the field and staying coachable",
    "rv": "",
    "conf": "Dance as I explained above.",
    "sp": "Volleyball, dance"
  },
  {
    "n": "Mya Matthias",
    "g": 11,
    "gn": "F",
    "ph": "7159652340",
    "em": "Shelly Matthias",
    "p1": "",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "Learn new things and try a new sport.",
    "imp": "Both of them",
    "pg": "Stay consistent with school and keep my grades up.",
    "rv": "Resilience",
    "conf": "No",
    "sp": "N/A"
  },
  {
    "n": "Autumn Cooley",
    "g": 12,
    "gn": "F",
    "ph": "715-560-5316",
    "em": "Jenny R 715-560-3132",
    "p1": "4x800",
    "p2": "4x4",
    "pr": "(800) 2:38 \n(400) 1:07\n(200) :25",
    "inj": "Torn hip labrum",
    "goal": "Make it back to sectionals in 4x8",
    "imp": "4x8",
    "pg": "Keep running through the pain till my limit",
    "rv": "Respect. Attitude",
    "conf": "No",
    "sp": "Tennis"
  },
  {
    "n": "Naomi Thomas",
    "g": 10,
    "gn": "F",
    "ph": "7159657715",
    "em": "Mindy Thomas 7159652377",
    "p1": "Shot put",
    "p2": "discus",
    "pr": "",
    "inj": "no",
    "goal": "throw farther and get stronger",
    "imp": "shot put",
    "pg": "Consistency",
    "rv": "Resilience",
    "conf": "no",
    "sp": "none"
  },
  {
    "n": "Lindsay Kahn",
    "g": 12,
    "gn": "F",
    "ph": "715-314-0219",
    "em": "Mary Kahn 507-421-7216",
    "p1": "1600meter",
    "p2": "800meter",
    "pr": "3200 meter- 12:28\n1600 meter- 5:39\n800 meter- 2:31",
    "inj": "No",
    "goal": "Make it to State in either 3 of my events. Get PRs in all 3 events this year.",
    "imp": "1600m",
    "pg": "I want to take a leader role this year for the group.",
    "rv": "Resilience",
    "conf": "Not that I know of.",
    "sp": "Cross Country"
  },
  {
    "n": "Alexis Zuleger",
    "g": 12,
    "gn": "F",
    "ph": "(715)560-8397",
    "em": "John Zuleger",
    "p1": "200, 200 rely",
    "p2": "4x400",
    "pr": "Idk",
    "inj": "Pulled my calf muscle but not bad",
    "goal": "Run the best I can",
    "imp": "200 or 400",
    "pg": "Be positive",
    "rv": "Attitude",
    "conf": "No",
    "sp": "None"
  },
  {
    "n": "Raylin Rothmeier",
    "g": 10,
    "gn": "F",
    "ph": "7159659879",
    "em": "Lindsay Campbell 715-965-0156",
    "p1": "Triple jump",
    "p2": "400",
    "pr": "N/A",
    "inj": "No",
    "goal": "To improve and break personal records as the season continues",
    "imp": "Triple jump",
    "pg": "I would like to show leadership and determination",
    "rv": "Discipline",
    "conf": "I will have a few practices I have to miss due to having gymnastics practice in Marshfield.",
    "sp": "Tennis, gymnastics"
  },
  {
    "n": "Tristan Newberry",
    "g": 10,
    "gn": "M",
    "ph": "715 574 5973",
    "em": "Rachel Newberry (608) 518-8753",
    "p1": "Long jump",
    "p2": "100",
    "pr": "N/A",
    "inj": "N/A",
    "goal": "To try my hardest at something new",
    "imp": "Long jump",
    "pg": "Leadership",
    "rv": "Discipline",
    "conf": "Nope",
    "sp": "N/A"
  },
  {
    "n": "Jordan Lavin",
    "g": 11,
    "gn": "M",
    "ph": "715-960-8576",
    "em": "Liz nuernburger 715-560-1399",
    "p1": "Pole vault",
    "p2": "N/A",
    "pr": "12ft",
    "inj": "N/A",
    "goal": "To jump 14ft or higher and win state",
    "imp": "Pole vault",
    "pg": "To push my teammates",
    "rv": "Sportsmanship",
    "conf": "No",
    "sp": "Cross country"
  },
  {
    "n": "Eric Paul",
    "g": 10,
    "gn": "M",
    "ph": "715-965-5094",
    "em": "Lynn Paul\u2014715-965-8354",
    "p1": "100m",
    "p2": "Triple Jump",
    "pr": "No clue",
    "inj": "No",
    "goal": "Get faster and jump farther",
    "imp": "Triple jump",
    "pg": "Consistency",
    "rv": "Sportsmanship",
    "conf": "No",
    "sp": "Soccer, archery"
  },
  {
    "n": "Nevyn Gripentrog",
    "g": 11,
    "gn": "M",
    "ph": "7158973190",
    "em": "Nicole Gripentrog 7158973189",
    "p1": "800",
    "p2": "1600",
    "pr": "I don't know",
    "inj": "No",
    "goal": "Improve from laat year",
    "imp": "800",
    "pg": "Consistency",
    "rv": "Resilience",
    "conf": "No",
    "sp": "Cross Country"
  },
  {
    "n": "Will Daniels",
    "g": 12,
    "gn": "M",
    "ph": "7156796798",
    "em": "Ray Daniels 715-560-2506",
    "p1": "300m Hurdles",
    "p2": "110m Hurdles",
    "pr": "40.3 -300m hurdles.   15.8 -110m hurdles",
    "inj": "ankle tweak",
    "goal": "podium at state",
    "imp": "300m Hurdles",
    "pg": "Be a great teammate",
    "rv": "Discipline",
    "conf": "Yes, wednesdays coaching aau",
    "sp": "Basketball, XC"
  },
  {
    "n": "Ryker Hallam",
    "g": 12,
    "gn": "M",
    "ph": "715-314-9042",
    "em": "Elizabeth Hallam 715-314-2048",
    "p1": "200 Relay",
    "p2": "Long Jump",
    "pr": "",
    "inj": "No",
    "goal": "To get 1st place",
    "imp": "To Jump farther on the long Jump",
    "pg": "To do my best",
    "rv": "Discipline",
    "conf": "Not that I know of",
    "sp": "Basketball"
  },
  {
    "n": "Rivalee Stokes",
    "g": 12,
    "gn": "F",
    "ph": "7159655923",
    "em": "Katie stokes 7155701872",
    "p1": "Discus",
    "p2": "100",
    "pr": "",
    "inj": "No",
    "goal": "Go to state",
    "imp": "Discus",
    "pg": "Be the best I can I can be",
    "rv": "",
    "conf": "",
    "sp": "Hockey"
  },
  {
    "n": "Ethan Jacobsen",
    "g": 10,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "High Jump",
    "p2": "Hurdles",
    "pr": "",
    "inj": "No",
    "goal": "Improve in all events",
    "imp": "High Jump",
    "pg": "Consistency",
    "rv": "Discipline",
    "conf": "No",
    "sp": ""
  },
  {
    "n": "Jasper Stokes",
    "g": 10,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Triple Jump",
    "p2": "High Jump",
    "pr": "TJ 37-5.5 HJ 5-0 LJ 18-0",
    "inj": "No",
    "goal": "State qualifier in triple jump",
    "imp": "Triple Jump",
    "pg": "Leadership",
    "rv": "Discipline",
    "conf": "No",
    "sp": ""
  },
  {
    "n": "Jovenski Macrsaint-Vil",
    "g": 9,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Blake Thoreson",
    "g": 11,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Throws",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Taylor Klingbeil",
    "g": 11,
    "gn": "F",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Chelsea Dick",
    "g": 10,
    "gn": "F",
    "ph": "",
    "em": "",
    "p1": "",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Alessia Salamin",
    "g": 10,
    "gn": "F",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Ellie Eckert",
    "g": 11,
    "gn": "F",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Mariah Salzer",
    "g": 9,
    "gn": "F",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Drayton Britz",
    "g": 9,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Max Losiewicz",
    "g": 9,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Pole Vault",
    "p2": "",
    "pr": "9-6",
    "inj": "",
    "goal": "",
    "imp": "Pole Vault",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Tosh Satterwhite",
    "g": 9,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Christopher Dunn",
    "g": 11,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Parker Fogo",
    "g": 11,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Throws",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Alan Scheel",
    "g": 11,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Jaden Thao",
    "g": 10,
    "gn": "M",
    "ph": "",
    "em": "",
    "p1": "Sprints",
    "p2": "",
    "pr": "",
    "inj": "",
    "goal": "",
    "imp": "",
    "pg": "",
    "rv": "",
    "conf": "",
    "sp": ""
  },
  {
    "n": "Emmanuel Espinoza",
    "g": 10,
    "gn": "M",
    "ph": "7155743258",
    "em": "Dad 715-409-9913",
    "p1": "100 meter dash",
    "p2": "800 meter run relay",
    "pr": "",
    "inj": "No",
    "goal": "To improve my running and make it to varsity",
    "imp": "200 meter dash",
    "pg": "Consistency",
    "rv": "Resilience",
    "conf": "No",
    "sp": "Cross country, basketball"
  },
];

export const MEETS = [
  {id:1,date:"2026-03-24",name:"Marshfield Boys Indoor",loc:"Marshfield",g:"B",type:"away",bus:"2:30 PM",start:"4:30 PM",deadline:"ASAP",hasLineup:true},
  {id:2,date:"2026-03-26",name:"Marshfield Girls Indoor",loc:"Marshfield",g:"G",type:"away",bus:"2:30 PM",start:"4:45 PM",deadline:"Wed 3/25 @ 5PM",hasLineup:true,hasResults:true},
  {id:3,date:"2026-03-27",name:"Northern Badger Classic",loc:"UW-Stout",g:"B/G",type:"away",bus:"12:30 PM",start:"3:00 PM",deadline:"Wed 3/25 @ NOON",hasResults:true},
  {id:4,date:"2026-04-02",name:"Stout Elite Meet",loc:"UW-Stout",g:"B/G",type:"away",bus:"12:30 PM",start:"3:00 PM",deadline:"Sun 3/29 @ midnight"},
  {id:5,date:"2026-04-04",name:"UWSP Distance Carnival",loc:"Stevens Point",g:"B/G",type:"away",start:"2:00 PM",deadline:"Thu 4/2 @ 8PM"},
  {id:6,date:"2026-04-09",name:"Medford Home Invite",loc:"Medford",g:"B/G",type:"home",start:"4:00 PM",hasResults:true},
  {id:7,date:"2026-04-14",name:"Holy Cow We're Hosting Invitational",loc:"Stratford",g:"B/G",type:"away",bus:"2:15 PM",start:"4:00 PM",hasLineup:true},
  {id:8,date:"2026-04-23",name:"Medford Home Invite #2",loc:"Medford",g:"B/G",type:"home",start:"4:00 PM"},
  {id:9,date:"2026-05-01",name:"Spencer Invitational",loc:"Spencer",g:"B/G",type:"away",bus:"2:30 PM",start:"4:15 PM"},
  {id:10,date:"2026-05-05",name:"Lakeland Meet",loc:"Lakeland",g:"B/G",type:"away",bus:"1:15 PM",start:"4:00 PM"},
  {id:11,date:"2026-05-08",name:"Merrill Invitational",loc:"Merrill",g:"B/G",type:"away",start:"5:00 PM"},
  {id:12,date:"2026-05-12",name:"Marathon Meet",loc:"Marathon",g:"B/G",type:"away",bus:"2:30 PM",start:"4:30 PM"},
  {id:13,date:"2026-05-15",name:"Marshfield Invitational",loc:"Marshfield",g:"B/G",type:"away",bus:"2:00 PM",start:"4:00 PM"},
  {id:14,date:"2026-05-19",name:"GNC Conference",loc:"Rhinelander",g:"B/G",type:"conf",bus:"1:15 PM",start:"4:00 PM"},
  {id:15,date:"2026-05-26",name:"WIAA Regional",loc:"Medford",g:"B/G",type:"regional",start:"4:00 PM"},
  {id:16,date:"2026-05-29",name:"WIAA Sectional",loc:"Rice Lake",g:"B/G",type:"sectional",bus:"1:00 PM",start:"4:00 PM"},
];

export const LOCATIONS = {
  "Medford":{lat:45.1386,lon:-90.3412,zip:"54451"},
  "Marshfield":{lat:44.6688,lon:-90.1718},
  "UW-Stout":{lat:44.8755,lon:-91.9193},
  "Stevens Point":{lat:44.5236,lon:-89.5746},
  "Stratford":{lat:44.8017,lon:-90.0787},
  "Spencer":{lat:44.7563,lon:-90.2970},
  "Lakeland":{lat:45.8911,lon:-89.2451},
  "Merrill":{lat:45.1810,lon:-89.6832},
  "Marathon":{lat:44.9275,lon:-89.8401},
  "Rhinelander":{lat:45.6366,lon:-89.4121},
  "Rice Lake":{lat:45.5060,lon:-91.7382},
};

export const ACTIONS = [
  {id:1,t:"✅ Entries confirmed — Holy Cow Invitational @ Stratford (51 entries)",d:"2026-04-12",p:"h"},
  {id:2,t:"🚌 Bus departs 2:15 PM — confirm bus driver + headcount",d:"2026-04-13",p:"h"},
  {id:3,t:"📋 Print lineup sheets + relay cards for coaches",d:"2026-04-13",p:"h"},
  {id:4,t:"🏥 Confirm trainer/ATC availability for meet",d:"2026-04-13",p:"h"},
  {id:5,t:"📱 Send meet-day reminder to parents (TeamReach)",d:"2026-04-13",p:"m"},
  {id:6,t:"⚠️ Monitor Rivalee (limited) + Autumn (limited) warmups",d:"2026-04-13",p:"h"},
  {id:7,t:"🎯 Review relay handoff assignments — 2x 4x100 teams entered",d:"2026-04-13",p:"m"},
  {id:8,t:"📋 Enter Medford Home Invite #2 (4/23) — deadline TBD",d:"2026-04-20",p:"m"},
];

export const KNOWN_STATUS = {
  "Evan Pagel":"limited",
  "Sawyer Hoops":"modified",
  "Colton Long":"modified",
  "Autumn Cooley":"limited",
  "Aliyah Pilgrim":"unavailable",
  "Avery Losiewicz":"injured",
  "Rivalee Stokes":"limited",
};
// ═══════════════════════════════════════════════
// MEET RESULTS — Marshfield Tiger Boys Invite 3/24
// ═══════════════════════════════════════════════
export const RESULTS = [
  {meet:"UWSP Distance Carnival",date:"2026-04-04",id:5,teams:32,data:[
    {a:"Judah Wipf",e:"800 Meter Run",lvl:"V",mark:"2:15.43",seed:"2:18.67",place:14,of:50,pr:1},
    {a:"Angus Hamland",e:"1600 Meter Run",lvl:"V",mark:"5:32.16",seed:"5:14.19",place:4,of:40,pr:0},
    {a:"Melanie Richter",e:"1600 Meter Run",lvl:"FR",mark:"5:55.05",seed:"6:04.40",place:2,of:15,pr:1},
  ]},
  {meet:"Marshfield Boys",date:"2026-03-24",id:1,teams:15,data:[
    {a:"Colton Long",e:"60yd Dash",lvl:"V",mark:"7.23",seed:"7.40",place:13,of:25,pr:1},
    {a:"Erik Paul",e:"60yd Dash",lvl:"V",mark:"7.58",seed:"7.87",place:20,of:25,pr:1},
    {a:"Axel Brushaber",e:"220yd Dash",lvl:"V",mark:"27.52",seed:"27.82",place:9,of:23,pr:1},
    {a:"Erik Paul",e:"220yd Dash",lvl:"V",mark:"28.78",seed:"28.00",place:17,of:23,pr:0},
    {a:"Sawyer Hoops",e:"440yd Dash",lvl:"V",mark:"1:01.42",seed:"1:05.00",place:5,of:18,pr:1},
    {a:"Judah Wipf",e:"880yd Run",lvl:"V",mark:"2:26.43",seed:"2:36.00",place:6,of:20,pr:1},
    {a:"Angus Hamland",e:"Mile Run",lvl:"V",mark:"5:57.34",seed:"5:32.79",place:11,of:18,pr:0},
    {a:"Luke Klapatauskas",e:"60m Hurdles",lvl:"V",mark:"9.08",seed:"9.50",place:4,of:11,pr:1},
    {a:"Luke Klapatauskas",e:"Triple Jump",lvl:"V",mark:"37-4",seed:"37-5.5",place:2,of:10,pr:0},
    {a:"Jasper Stokes",e:"Long Jump",lvl:"V",mark:"16-5",seed:"18-0",place:11,of:18,pr:0},
    {a:"Max Losiewicz",e:"Pole Vault",lvl:"V",mark:"11-0",seed:"9-6",place:8,of:13,pr:1},
    {a:"Jordan Lavin",e:"Pole Vault",lvl:"V",mark:"11-0",seed:"9-6",place:9,of:13,pr:1},
    {a:"Logan Langdon",e:"Shot Put",lvl:"V",mark:"37-9.5",seed:"34-7",place:6,of:24,pr:1},
    {a:"Johnathon Bartnick",e:"Shot Put",lvl:"V",mark:"31-11",seed:"30-5.5",place:15,of:24,pr:1},
    {a:"Medford Area",e:"4x440 Relay",lvl:"V",mark:"4:13.43",seed:"",place:5,of:8,pr:0},
    {a:"Medford Area",e:"4x880 Relay",lvl:"V",mark:"9:54.30",seed:"",place:3,of:5,pr:0},
    {a:"Tosh Satterwhite",e:"60yd Dash",lvl:"JV",mark:"7.31",seed:"",place:23,of:78,pr:0},
    {a:"Parker Judnic",e:"60yd Dash",lvl:"JV",mark:"7.61",seed:"",place:39,of:78,pr:0},
    {a:"Draven Dums",e:"220yd Dash",lvl:"JV",mark:"29.18",seed:"",place:20,of:42,pr:0},
    {a:"Parker Judnic",e:"220yd Dash",lvl:"JV",mark:"30.41",seed:"",place:25,of:42,pr:0},
    {a:"Ryker Hallam",e:"440yd Dash",lvl:"JV",mark:"1:20.18",seed:"",place:22,of:23,pr:0},
    {a:"Peyton Reid",e:"880yd Run",lvl:"JV",mark:"2:33.29",seed:"",place:2,of:18,pr:0},
    {a:"Nevyn Gripentrog",e:"880yd Run",lvl:"JV",mark:"2:59.19",seed:"",place:10,of:18,pr:0},
    {a:"Tristan Newberry",e:"Mile Run",lvl:"JV",mark:"6:55.37",seed:"",place:8,of:8,pr:0},
    {a:"Draven Dums",e:"High Jump",lvl:"JV",mark:"4-8",seed:"",place:5,of:7,pr:0},
    {a:"Luca Gumy",e:"Long Jump",lvl:"JV",mark:"15-3.75",seed:"",place:6,of:27,pr:0},
    {a:"Jaden Thao",e:"Long Jump",lvl:"JV",mark:"14-7",seed:"",place:17,of:27,pr:0},
    {a:"Ryker Hallam",e:"Long Jump",lvl:"JV",mark:"9-9.5",seed:"",place:27,of:27,pr:0},
    {a:"Axel Brushaber",e:"Triple Jump",lvl:"JV",mark:"36-3.5",seed:"",place:1,of:4,pr:0},
    {a:"Erik Paul",e:"Triple Jump",lvl:"JV",mark:"31-6",seed:"",place:3,of:4,pr:0},
    {a:"Bentley Cooley",e:"Pole Vault",lvl:"JV",mark:"8-0",seed:"",place:3,of:5,pr:0},
    {a:"Parker Fogo",e:"Shot Put",lvl:"JV",mark:"30-2",seed:"",place:14,of:39,pr:0},
    {a:"Logan Schmidt",e:"Shot Put",lvl:"JV",mark:"26-1.75",seed:"",place:26,of:39,pr:0},
    {a:"Reuben Barnhart",e:"Shot Put",lvl:"JV",mark:"25-10.75",seed:"",place:27,of:39,pr:0},
    {a:"Paxton Hamland",e:"Shot Put",lvl:"JV",mark:"21-11.5",seed:"",place:33,of:39,pr:0},
    {a:"Medford Area",e:"4x440 Relay",lvl:"JV",mark:"4:33.61",seed:"",place:4,of:4,pr:0},
    {a:"Medford Area",e:"4x880 Relay",lvl:"JV",mark:"11:50.03",seed:"",place:2,of:2,pr:0},
  ]},
  {meet:"Marshfield Girls",date:"2026-03-26",id:2,teams:15,data:[
    {a:"Lindsay Kahn",e:"Mile Run",lvl:"V",mark:"5:56.00",seed:"6:14.63",place:1,of:21,pr:1},
    {a:"Jordyn Grant",e:"Triple Jump",lvl:"V",mark:"30-0.00",seed:"30-10",place:4,of:19,pr:0},
    {a:"Jordyn Grant",e:"220yd Dash",lvl:"V",mark:"31.31",seed:"31.34",place:8,of:26,pr:1},
    {a:"Melanie Richter",e:"880yd Run",lvl:"V",mark:"2:51.62",seed:"",place:10,of:26,pr:1},
    {a:"Taylor Klingbeil",e:"Long Jump",lvl:"V",mark:"13-8.50",seed:"",place:12,of:31,pr:1},
    {a:"Jordyn Grant",e:"60yd Dash",lvl:"V",mark:"8.09",seed:"",place:14,of:38,pr:1},
    {a:"Rivalee Stokes",e:"Shot Put",lvl:"V",mark:"29-5.25",seed:"28-6.5",place:14,of:43,pr:1},
    {a:"Alexis Zuleger",e:"220yd Dash",lvl:"V",mark:"33.59",seed:"31.46",place:15,of:26,pr:0},
    {a:"Raylin Rothmeier",e:"Long Jump",lvl:"V",mark:"12-7.50",seed:"",place:16,of:31,pr:0},
    {a:"Cora Semrau",e:"60m Hurdles",lvl:"V",mark:"11.99",seed:"",place:16,of:18,pr:1},
    {a:"Willow Dassow",e:"880yd Run",lvl:"V",mark:"2:56.50",seed:"3:03.29",place:17,of:26,pr:1},
    {a:"Sada Carstensen",e:"Shot Put",lvl:"V",mark:"27-10.75",seed:"",place:21,of:43,pr:1},
    {a:"Alexis Zuleger",e:"60yd Dash",lvl:"V",mark:"8.62",seed:"",place:24,of:38,pr:0},
    {a:"Ellie Eckert",e:"Long Jump",lvl:"V",mark:"9-8.75",seed:"10-7.75",place:26,of:31,pr:0},
    {a:"Naomi Thomas",e:"Shot Put",lvl:"V",mark:"23-7.25",seed:"18-3.25",place:31,of:43,pr:1},
    {a:"Taylor Klingbeil",e:"220yd Dash",lvl:"JV",mark:"32.28",seed:"",place:7,of:69,pr:1},
    {a:"Savannah Hebert",e:"Shot Put",lvl:"JV",mark:"22-0.50",seed:"",place:14,of:39,pr:1},
    {a:"Mya Matthias",e:"Shot Put",lvl:"JV",mark:"21-0.50",seed:"",place:18,of:39,pr:1},
    {a:"Cora Semrau",e:"60yd Dash",lvl:"JV",mark:"8.50",seed:"",place:22,of:90,pr:1},
    {a:"Mariah Salzer",e:"440yd Dash",lvl:"JV",mark:"1:24.07",seed:"",place:22,of:25,pr:1},
    {a:"Chloe Pipkorn",e:"Shot Put",lvl:"JV",mark:"19-2.75",seed:"",place:28,of:39,pr:1},
    {a:"Alessia Salamin",e:"220yd Dash",lvl:"JV",mark:"34.87",seed:"",place:33,of:69,pr:1},
    {a:"Lucy Ulrich",e:"60yd Dash",lvl:"JV",mark:"8.81",seed:"",place:40,of:90,pr:1},
    {a:"Alessia Salamin",e:"60yd Dash",lvl:"JV",mark:"9.09",seed:"",place:53,of:90,pr:1},
    {a:"Ellie Eckert",e:"60yd Dash",lvl:"JV",mark:"9.24",seed:"",place:62,of:90,pr:1},
  ]},
  // ═══════════════════════════════════════════════
  // Northern Badger Classic 3/27
  // UW-Stout · Large School Division · B/G Combined
  // Note: event labels corrected where source data mismatched
  // Stokes/Gumy "PV" → LJ, Dassow "1600F" → 800, Ulrich "800" → 400, Gripentrog "3200" → 1600
  // ═══════════════════════════════════════════════,
  {meet:"Northern Badger",date:"2026-03-27",id:3,teams:0,data:[
    // ── BOYS ──
    {a:"Will Daniels",e:"55M Hurdles",lvl:"V",mark:"8.38",seed:"8.53",place:5,of:0,pr:1},
    {a:"Sawyer Hoops",e:"400M",lvl:"V",mark:"56.70",seed:"55.02",place:7,of:0,pr:1},
    {a:"Luke Klapatauskas",e:"Triple Jump",lvl:"V",mark:"38-01.50",seed:"37-5.5",place:8,of:0,pr:1},
    {a:"Judah Wipf",e:"800M",lvl:"V",mark:"2:16.03",seed:"2:18.67",place:9,of:0,pr:1},
    {a:"Logan Langdon",e:"Shot Put",lvl:"V",mark:"38-04.75",seed:"34-7",place:12,of:0,pr:1},
    {a:"Jordan Lavin",e:"Pole Vault",lvl:"V",mark:"12-06.00",seed:"9-6",place:3,of:0,pr:1},
    {a:"Max Losiewicz",e:"Pole Vault",lvl:"V",mark:"10-06.00",seed:"9-6",place:7,of:0,pr:0},
    {a:"Jonathan Bartnik",e:"Shot Put",lvl:"V",mark:"35-10.75",seed:"",place:16,of:0,pr:1},
    {a:"Luke Klapatauskas",e:"55M Hurdles",lvl:"V",mark:"9.19",seed:"",place:17,of:0,pr:0},
    {a:"Jasper Stokes",e:"Long Jump",lvl:"V",mark:"16-11.50",seed:"14-11.75",place:17,of:0,pr:0},
    {a:"Luca Gumy",e:"Long Jump",lvl:"V",mark:"16-07.50",seed:"",place:18,of:0,pr:1},
    {a:"Angus Hamland",e:"1600M",lvl:"V",mark:"5:19.55",seed:"5:14.19",place:21,of:0,pr:0},
    {a:"Ethan Jacobsen",e:"400M",lvl:"V",mark:"1:05.41",seed:"",place:22,of:0,pr:0},
    {a:"Sawyer Hoops",e:"200M",lvl:"V",mark:"25.34",seed:"",place:29,of:0,pr:0,note:"Wildcard"},
    {a:"Nevyn Gripentrog",e:"1600M",lvl:"V",mark:"6:08.78",seed:"5:50.94",place:29,of:0,pr:0},
    {a:"Levi Zuleger",e:"200M",lvl:"V",mark:"25.69",seed:"26.61",place:33,of:0,pr:1},
    {a:"Axel Brushaber",e:"200M",lvl:"V",mark:"26.20",seed:"",place:39,of:0,pr:0},
    {a:"Axel Brushaber",e:"Triple Jump",lvl:"V",mark:"35-11.50",seed:"35-9",place:14,of:0,pr:0},
    {a:"Levi Zuleger",e:"55M Dash",lvl:"V",mark:"7.57",seed:"",place:47,of:0,pr:0},
    {a:"Erik Paul",e:"55M Dash",lvl:"V",mark:"7.64",seed:"",place:50,of:0,pr:0},
    {a:"Evan Pagel",e:"3200M",lvl:"V",mark:"13:00.23",seed:"11:40.56",place:16,of:0,pr:0},
    {a:"Peyton Reid",e:"800M",lvl:"V",mark:"2:23.59",seed:"2:28.03",place:0,of:0,pr:1},
    {a:"Medford Area",e:"4x400 Relay",lvl:"V",mark:"4:07.00",seed:"3:33.30",place:0,of:0,pr:0},
    // ── GIRLS ──
    {a:"Jordyn Grant",e:"Triple Jump",lvl:"V",mark:"32-02.25",seed:"32-8.5",place:4,of:0,pr:0},
    {a:"Rivalee Stokes",e:"Shot Put",lvl:"V",mark:"30-10.00",seed:"31-11.5",place:5,of:0,pr:1},
    {a:"Lindsay Kahn",e:"1600M",lvl:"V",mark:"5:38.46",seed:"5:39.86",place:6,of:0,pr:1},
    {a:"Melanie Richter",e:"800M",lvl:"V",mark:"2:43.13",seed:"2:41.92",place:7,of:0,pr:1},
    {a:"Taylor Klingbeil",e:"400M",lvl:"V",mark:"1:11.15",seed:"",place:8,of:0,pr:1},
    {a:"Melanie Richter",e:"1600M",lvl:"V",mark:"6:05.57",seed:"6:04.51",place:9,of:0,pr:0},
    {a:"Rivalee Stokes",e:"55M Dash",lvl:"V",mark:"7.96",seed:"8.11",place:11,of:0,pr:1},
    {a:"Cora Semrau",e:"55M Hurdles",lvl:"V",mark:"12.22",seed:"",place:18,of:0,pr:0},
    {a:"Jordyn Grant",e:"55M Dash",lvl:"V",mark:"8.11",seed:"8.25",place:19,of:0,pr:1},
    {a:"Naomi Thomas",e:"Shot Put",lvl:"V",mark:"23-02.00",seed:"24-6.5",place:22,of:0,pr:0},
    {a:"Alexis Zuleger",e:"200M",lvl:"V",mark:"32.49",seed:"29.81",place:34,of:0,pr:0},
    {a:"Willow Dassow",e:"800M",lvl:"V",mark:"2:54.74",seed:"2:43.84",place:0,of:0,pr:0},
    {a:"Lucy Ulrich",e:"400M",lvl:"V",mark:"1:20.91",seed:"",place:18,of:0,pr:1},
  ]},
  // ═══════════════════════════════════════════════
  // Medford Early Bird Invite 4/9
  // 5 teams · Medford HS · B/G Combined
  // HIGHLIGHTS: Rivalee Stokes won Shot Put (32-2 PR) + Discus (124-6 SB);
  //  Luke Klapatauskas won 300m Hurdles; Logan Langdon won Boys Discus;
  //  Medford Boys 4x100 A + 4x400 A + Girls 4x800 A all took 1st.
  // ═══════════════════════════════════════════════,
  {meet:"Medford Early Bird",date:"2026-04-09",id:6,teams:5,data:[
    // ── BOYS ──
    {a:"Colton Long",e:"100 Meters",lvl:"V",mark:"12.16",seed:"",place:5,of:16,pr:0},
    {a:"Eric Paul",e:"100 Meters",lvl:"V",mark:"13.02",seed:"",place:11,of:16,pr:1},
    {a:"Tosh Satterwhite",e:"100 Meters",lvl:"V",mark:"13.02",seed:"",place:11,of:16,pr:1},
    {a:"Jaden Thao",e:"100 Meters",lvl:"V",mark:"13.42",seed:"",place:13,of:16,pr:1},
    {a:"Parker Judnic",e:"100 Meters",lvl:"V",mark:"13.49",seed:"",place:14,of:16,pr:1},
    {a:"Draven Dums",e:"100 Meters",lvl:"V",mark:"13.53",seed:"",place:16,of:16,pr:1},
    {a:"Levi Zulegar",e:"200 Meters",lvl:"V",mark:"25.54",seed:"",place:5,of:13,pr:0},
    {a:"Eric Paul",e:"200 Meters",lvl:"V",mark:"27.26",seed:"",place:8,of:13,pr:1},
    {a:"Draven Dums",e:"200 Meters",lvl:"V",mark:"27.97",seed:"",place:11,of:13,pr:1},
    {a:"Sawyer Hoops",e:"400 Meters",lvl:"V",mark:"55.60",seed:"",place:2,of:11,pr:0},
    {a:"Ethan Jacobsen",e:"400 Meters",lvl:"V",mark:"58.05",seed:"",place:5,of:11,pr:1},
    {a:"Jasper Stokes",e:"400 Meters",lvl:"V",mark:"1:05.64",seed:"",place:10,of:11,pr:1},
    {a:"Emmanuel Espinoza",e:"800 Meters",lvl:"V",mark:"2:30.26",seed:"",place:5,of:8,pr:1},
    {a:"Tristan Newberry",e:"800 Meters",lvl:"V",mark:"2:50.32",seed:"",place:7,of:8,pr:1},
    {a:"Angus Hamland",e:"1600 Meters",lvl:"V",mark:"5:27.18",seed:"",place:3,of:7,pr:0},
    {a:"Nevyn Gripentrog",e:"1600 Meters",lvl:"V",mark:"5:56.62",seed:"",place:5,of:7,pr:0},
    {a:"Luke Klapatauskas",e:"110m Hurdles",lvl:"V",mark:"17.87",seed:"",place:2,of:6,pr:1},
    {a:"Luke Klapatauskas",e:"300m Hurdles",lvl:"V",mark:"45.19",seed:"",place:1,of:8,pr:0},
    {a:"Medford Area",e:"4x100 Relay",lvl:"V",mark:"50.28",seed:"",place:1,of:4,pr:0,note:"Hallam/Long/Brushaber/Zulegar"},
    {a:"Medford Area B",e:"4x100 Relay",lvl:"V",mark:"53.97",seed:"",place:4,of:4,pr:0,note:"Judnic/Preuss/Satterwhite/Dums"},
    {a:"Medford Area",e:"4x400 Relay",lvl:"V",mark:"3:54.95",seed:"",place:1,of:4,pr:0,note:"Hoops/Jacobsen/Reid/Wipf"},
    {a:"Medford Area",e:"4x800 Relay",lvl:"V",mark:"9:37.67",seed:"",place:2,of:3,pr:0,note:"Pagel/Gripentrog/Reid/Hamland"},
    {a:"Blake Thorson",e:"Shot Put",lvl:"V",mark:"35-3",seed:"",place:4,of:19,pr:1},
    {a:"Jonathan Bartnik",e:"Shot Put",lvl:"V",mark:"33-7.5",seed:"",place:6,of:19,pr:1},
    {a:"Parker Fogo",e:"Shot Put",lvl:"V",mark:"31-11",seed:"",place:7,of:19,pr:1},
    {a:"Logan Langdon",e:"Shot Put",lvl:"V",mark:"31-10.5",seed:"",place:8,of:19,pr:0},
    {a:"Christopher Dunn",e:"Shot Put",lvl:"V",mark:"28-4",seed:"",place:11,of:19,pr:1},
    {a:"Jaden Thao",e:"Shot Put",lvl:"V",mark:"28-3.5",seed:"",place:12,of:19,pr:1},
    {a:"Reuben Barnhart",e:"Shot Put",lvl:"V",mark:"28-1",seed:"",place:13,of:19,pr:1},
    {a:"Logan Schmidt",e:"Shot Put",lvl:"V",mark:"24-6",seed:"",place:15,of:19,pr:1},
    {a:"Paxton Hamland",e:"Shot Put",lvl:"V",mark:"23-8",seed:"",place:17,of:19,pr:1},
    {a:"Logan Langdon",e:"Discus",lvl:"V",mark:"125-10",seed:"",place:1,of:16,pr:1},
    {a:"Jonathan Bartnik",e:"Discus",lvl:"V",mark:"90-8",seed:"",place:4,of:16,pr:1},
    {a:"Christopher Dunn",e:"Discus",lvl:"V",mark:"80-0",seed:"",place:5,of:16,pr:1},
    {a:"Parker Fogo",e:"Discus",lvl:"V",mark:"76-3",seed:"",place:6,of:16,pr:1},
    {a:"Logan Schmidt",e:"Discus",lvl:"V",mark:"68-8",seed:"",place:8,of:16,pr:1},
    {a:"Reuben Barnhart",e:"Discus",lvl:"V",mark:"65-9",seed:"",place:11,of:16,pr:1},
    {a:"Blake Thorson",e:"Discus",lvl:"V",mark:"63-6",seed:"",place:13,of:16,pr:1},
    {a:"Paxton Hamland",e:"Discus",lvl:"V",mark:"47-7",seed:"",place:16,of:16,pr:1},
    {a:"Eric Paul",e:"High Jump",lvl:"V",mark:"5-0",seed:"",place:2,of:4,pr:1},
    {a:"Jordan Lavin",e:"Pole Vault",lvl:"V",mark:"12-6",seed:"",place:1,of:7,pr:1},
    {a:"Max Losiewicz",e:"Pole Vault",lvl:"V",mark:"10-0",seed:"",place:3,of:7,pr:1},
    {a:"Bentley Cooley",e:"Pole Vault",lvl:"V",mark:"8-6",seed:"",place:6,of:7,pr:1},
    {a:"Xander Cynor",e:"Pole Vault",lvl:"V",mark:"6-0",seed:"",place:7,of:7,pr:1},
    {a:"Jaden Thao",e:"Long Jump",lvl:"V",mark:"14-1",seed:"",place:7,of:11,pr:0},
    {a:"Jasper Stokes",e:"Long Jump",lvl:"V",mark:"14-1",seed:"",place:8,of:11,pr:1},
    {a:"Ryker Hallam",e:"Long Jump",lvl:"V",mark:"9-9.5",seed:"",place:11,of:11,pr:1},
    {a:"Axel Brushaber",e:"Triple Jump",lvl:"V",mark:"38-4.5",seed:"",place:3,of:10,pr:1},
    {a:"Luke Klapatauskas",e:"Triple Jump",lvl:"V",mark:"37-10.5",seed:"",place:4,of:10,pr:1},
    // ── GIRLS ──
    {a:"Rivalee Stokes",e:"100 Meters",lvl:"V",mark:"13.62",seed:"",place:4,of:12,pr:0},
    {a:"Jordyn Grant",e:"100 Meters",lvl:"V",mark:"13.84",seed:"",place:6,of:12,pr:1},
    {a:"Lucy Ulrich",e:"100 Meters",lvl:"V",mark:"15.27",seed:"",place:11,of:12,pr:1},
    {a:"Jordyn Grant",e:"200 Meters",lvl:"V",mark:"29.53",seed:"",place:5,of:14,pr:0},
    {a:"Alexis Zuleger",e:"200 Meters",lvl:"V",mark:"32.43",seed:"",place:8,of:14,pr:0},
    {a:"Lucy Ulrich",e:"200 Meters",lvl:"V",mark:"32.76",seed:"",place:9,of:14,pr:1},
    {a:"Aliyah Pilgrim",e:"400 Meters",lvl:"V",mark:"1:08.43",seed:"",place:2,of:5,pr:0},
    {a:"Willow Dassow",e:"800 Meters",lvl:"V",mark:"2:56.38",seed:"",place:6,of:8,pr:0},
    {a:"Lindsay Kahn",e:"1600 Meters",lvl:"V",mark:"5:53.31",seed:"",place:1,of:5,pr:0},
    {a:"Melanie Richter",e:"1600 Meters",lvl:"V",mark:"6:04.40",seed:"",place:2,of:5,pr:1},
    {a:"Lindsay Kahn",e:"3200 Meters",lvl:"V",mark:"12:50.19",seed:"",place:1,of:2,pr:0},
    {a:"Cora Semrau",e:"100m Hurdles",lvl:"V",mark:"19.46",seed:"",place:1,of:5,pr:0},
    {a:"Cora Semrau",e:"300m Hurdles",lvl:"V",mark:"59.00",seed:"",place:3,of:7,pr:0},
    {a:"Medford Area",e:"4x100 Relay",lvl:"V",mark:"58.81",seed:"",place:2,of:3,pr:0,note:"Stokes/Zuleger/Eckert/Grant"},
    {a:"Medford Area",e:"4x200 Relay",lvl:"V",mark:"2:09.50",seed:"",place:3,of:4,pr:0,note:"Ulrich/Salamin/Salzer/Eckert"},
    {a:"Medford Area",e:"4x800 Relay",lvl:"V",mark:"11:12.89",seed:"",place:1,of:4,pr:0,note:"Cooley/Richter/Dassow/Kahn"},
    {a:"Rivalee Stokes",e:"Shot Put",lvl:"V",mark:"32-2",seed:"",place:1,of:20,pr:1,note:"Meet high; +3'3\" over Stratford meet record"},
    {a:"Sada Carstensen",e:"Shot Put",lvl:"V",mark:"29-7",seed:"",place:4,of:20,pr:1},
    {a:"Savannah Hebert",e:"Shot Put",lvl:"V",mark:"24-3",seed:"",place:9,of:20,pr:1},
    {a:"Naomi Thomas",e:"Shot Put",lvl:"V",mark:"22-8",seed:"",place:14,of:20,pr:0},
    {a:"Chloe Pipkorn",e:"Shot Put",lvl:"V",mark:"20-11.5",seed:"",place:16,of:20,pr:1},
    {a:"Mya Matthias",e:"Shot Put",lvl:"V",mark:"19-10",seed:"",place:19,of:20,pr:1},
    {a:"Rivalee Stokes",e:"Discus",lvl:"V",mark:"124-6",seed:"",place:1,of:20,pr:0,note:"Meet high; +16'1\" over own Stratford meet record"},
    {a:"Sada Carstensen",e:"Discus",lvl:"V",mark:"77-2",seed:"",place:4,of:20,pr:1},
    {a:"Mya Matthias",e:"Discus",lvl:"V",mark:"64-0",seed:"",place:9,of:20,pr:1},
    {a:"Savannah Hebert",e:"Discus",lvl:"V",mark:"63-2",seed:"",place:10,of:20,pr:1},
    {a:"Naomi Thomas",e:"Discus",lvl:"V",mark:"47-10",seed:"",place:18,of:20,pr:0},
    {a:"Chloe Pipkorn",e:"Discus",lvl:"V",mark:"39-0",seed:"",place:20,of:20,pr:1},
    {a:"Alessia Salamin",e:"Long Jump",lvl:"V",mark:"10-10.5",seed:"",place:7,of:9,pr:1},
    {a:"Ellie Eckert",e:"Long Jump",lvl:"V",mark:"7-9",seed:"",place:9,of:9,pr:0},
    {a:"Jordyn Grant",e:"Triple Jump",lvl:"V",mark:"30-1.25",seed:"",place:2,of:8,pr:0},
  ]}
];

// ═══════════════════════════════════════════════
// MEET ENTRIES — Holy Cow We're Hosting Invitational 4/13
// Confirmed entries from MileSplit as of 4/12/2026 10:35 PM
// ═══════════════════════════════════════════════
export const MEET_ENTRIES = {
  meetId: 7,
  meet: "Holy Cow We're Hosting Invitational",
  date: "2026-04-13",
  loc: "Stratford",
  boysEntries: 31,
  girlsEntries: 20,
  totalEntries: 51,
  events: [
    // ── GIRLS ──
    {event:"Girls 100m",athletes:[
      {n:"Jordyn Grant",seed:"13.84"},{n:"Alessia Salamin",seed:"14.51"},{n:"Rivalee Stokes",seed:"13.37"},{n:"Lucy Ulrich",seed:"15.27"}
    ]},
    {event:"Girls 200m",athletes:[
      {n:"Taylor Klingbeil",seed:"31.50"},{n:"Aliyah Pilgrim",seed:"28.39"},{n:"Alexis Zuleger",seed:"29.81"}
    ]},
    {event:"Girls 400m",athletes:[
      {n:"Taylor Klingbeil",seed:"1:11.00"},{n:"Aliyah Pilgrim",seed:"1:03.79"},{n:"Raylin Rothmeier",seed:"1:11.00"}
    ]},
    {event:"Girls 800m",athletes:[
      {n:"Autumn Cooley",seed:"2:40.00"},{n:"Melanie Richter",seed:"2:45.00"}
    ]},
    {event:"Girls 1600m",athletes:[
      {n:"Willow Dassow",seed:"6:15.40"},{n:"Lindsay Kahn",seed:"5:39.86"},{n:"Melanie Richter",seed:"6:04.40"}
    ]},
    {event:"Girls 3200m",athletes:[
      {n:"Lindsay Kahn",seed:"12:28.85"}
    ]},
    {event:"Girls 100m Hurdles",athletes:[
      {n:"Cora Semrau",seed:"19.35"}
    ]},
    {event:"Girls 300m Hurdles",athletes:[
      {n:"Cora Semrau",seed:"57.88"}
    ]},
    {event:"Girls 4x100m Relay",athletes:[
      {n:"Ellie Eckert"},{n:"Lucy Ulrich"},{n:"Jordyn Grant"},{n:"Rivalee Stokes"},{n:"Alexis Zuleger"}
    ]},
    {event:"Girls 4x200m Relay",athletes:[
      {n:"Ellie Eckert"},{n:"Cora Semrau"},{n:"Alexis Zuleger"},{n:"Jordyn Grant"},{n:"Taylor Klingbeil"}
    ]},
    {event:"Girls 4x800m Relay",athletes:[
      {n:"Autumn Cooley"},{n:"Melanie Richter"},{n:"Willow Dassow"},{n:"Lindsay Kahn"},{n:"Lucy Ulrich"}
    ]},
    {event:"Girls High Jump",athletes:[
      {n:"Taylor Klingbeil",seed:"4-0"}
    ]},
    {event:"Girls Long Jump",athletes:[
      {n:"Alessia Salamin",seed:"10-10.5"}
    ]},
    {event:"Girls Triple Jump",athletes:[
      {n:"Jordyn Grant",seed:"32-8.5"}
    ]},
    {event:"Girls Pole Vault",athletes:[
      {n:"Avery Losiewicz",seed:"10-0"}
    ]},
    {event:"Girls Discus",athletes:[
      {n:"Sada Carstensen",seed:"77-2"},{n:"Savannah Hebert",seed:"63-2"},{n:"Mya Matthias",seed:"64-0"},{n:"Chloe Pipkorn",seed:"39-0"},{n:"Rivalee Stokes",seed:"129-10"},{n:"Naomi Thomas",seed:"53-3"}
    ]},
    {event:"Girls Shot Put",athletes:[
      {n:"Sada Carstensen",seed:"29-7"},{n:"Savannah Hebert",seed:"24-3"},{n:"Mya Matthias",seed:"19-10"},{n:"Chloe Pipkorn",seed:"20-11.5"},{n:"Rivalee Stokes",seed:"32-2"},{n:"Naomi Thomas",seed:"24-7.75"}
    ]},
    // ── BOYS ──
    {event:"Boys 100m",athletes:[
      {n:"Draven Dums",seed:"13.53"},{n:"Colton Long",seed:"12.11"},{n:"Max Losiewicz",seed:"13.15"},{n:"Erik Paul",seed:"13.02"},{n:"Landon Preuss",seed:"13.39"},{n:"Tosh Satterwhite",seed:"13.02"},{n:"Jaden Thao",seed:"13.42"}
    ]},
    {event:"Boys 200m",athletes:[
      {n:"Axel Brushaber",seed:"26.05"},{n:"Draven Dums",seed:"27.97"},{n:"Erik Paul",seed:"27.26"},{n:"Landon Preuss",seed:"27.41"},{n:"Tosh Satterwhite",seed:"28.03"},{n:"Jaden Thao",seed:"28.21"},{n:"Levi Zulegar",seed:"25.04"}
    ]},
    {event:"Boys 400m",athletes:[
      {n:"Sawyer Hoops",seed:"55.02"},{n:"Ethan Jacobsen",seed:"58.05"},{n:"Tristan Newberry",seed:"58.05"},{n:"Peyton Reid",seed:"58.05"},{n:"Jasper Stokes",seed:"1:05.64"}
    ]},
    {event:"Boys 800m",athletes:[
      {n:"Emmanuel Espinoza",seed:"2:30.26"},{n:"Nevyn Gripentrog",seed:"2:25.85"},{n:"Tristan Newberry",seed:"2:50.32"},{n:"Judah Wipf",seed:"2:18.67"}
    ]},
    {event:"Boys 1600m",athletes:[
      {n:"Emmanuel Espinoza",seed:"5:56.73"},{n:"Nevyn Gripentrog",seed:"5:48.73"},{n:"Angus Hamland",seed:"5:14.19"},{n:"Evan Pagel",seed:"5:23.05"}
    ]},
    {event:"Boys 3200m",athletes:[
      {n:"Angus Hamland",seed:"11:00.00"}
    ]},
    {event:"Boys 110m Hurdles",athletes:[
      {n:"Parker Judnic",seed:"20.30"}
    ]},
    {event:"Boys 4x100m Relay A",athletes:[
      {n:"Ryker Hallam"},{n:"Colton Long"},{n:"Axel Brushaber"},{n:"Levi Zulegar"},{n:"Jordon Lavin"}
    ]},
    {event:"Boys 4x100m Relay B",athletes:[
      {n:"Landon Preuss"},{n:"Draven Dums"},{n:"Parker Judnic"},{n:"Tosh Satterwhite"},{n:"Max Losiewicz"}
    ]},
    {event:"Boys 4x200m Relay",athletes:[
      {n:"Levi Zulegar"},{n:"Peyton Reid"},{n:"Axel Brushaber"},{n:"Ethan Jacobsen"},{n:"Sawyer Hoops"}
    ]},
    {event:"Boys 4x400m Relay",athletes:[
      {n:"Sawyer Hoops"},{n:"Ethan Jacobsen"},{n:"Peyton Reid"},{n:"Judah Wipf"},{n:"Angus Hamland"}
    ]},
    {event:"Boys 4x800m Relay",athletes:[
      {n:"Evan Pagel"},{n:"Nevyn Gripentrog"},{n:"Peyton Reid"},{n:"Angus Hamland"},{n:"Emmanuel Espinoza"}
    ]},
    {event:"Boys High Jump",athletes:[
      {n:"Erik Paul",seed:"5-0"}
    ]},
    {event:"Boys Long Jump",athletes:[
      {n:"Emmanuel Espinoza",seed:"10-4.5"},{n:"Ryker Hallam",seed:"10-4.5"},{n:"Tristan Newberry",seed:"10-4.5"},{n:"Jasper Stokes",seed:"14-1"}
    ]},
    {event:"Boys Triple Jump",athletes:[
      {n:"Axel Brushaber",seed:"38-4.5"},{n:"Erik Paul",seed:"31-3.5"}
    ]},
    {event:"Boys Pole Vault",athletes:[
      {n:"Bentley Cooley",seed:"8-6"},{n:"Xander Cynor",seed:"6-0"},{n:"Jordon Lavin",seed:"12-6"},{n:"Max Losiewicz",seed:"10-0"}
    ]},
    {event:"Boys Discus",athletes:[
      {n:"Reuben Barnhart",seed:"65-9"},{n:"Johnathon Bartnick",seed:"90-8"},{n:"Christopher Dunn",seed:"85-11"},{n:"Parker Fogo",seed:"76-3"},{n:"Paxton Hamland",seed:"47-7"},{n:"Logan Langdon",seed:"125-10"},{n:"Logan Schmidt",seed:"68-8"}
    ]},
    {event:"Boys Shot Put",athletes:[
      {n:"Reuben Barnhart",seed:"28-1"},{n:"Johnathon Bartnick",seed:"34-2"},{n:"Christopher Dunn",seed:"29-3.5"},{n:"Parker Fogo",seed:"31-11"},{n:"Paxton Hamland",seed:"23-8"},{n:"Logan Langdon",seed:"33-6.5"},{n:"Logan Schmidt",seed:"24-6"}
    ]},
  ]
};


// === Missing exports for v6 page.js ===
export const CONFLICTS = [];
export const GUIDE_URLS = {};
export const RESULTS_URLS = {};
export const MEET_LINKS = {};
export const BADGER_BOYS = null;
export const BADGER_GIRLS = null;
export const STOUT_BOYS = null;
export const STOUT_GIRLS = null;
export const UWSP_BOYS = null;
export const UWSP_GIRLS = null;
export const EARLYBIRD_BOYS = null;
export const EARLYBIRD_GIRLS = null;
export const EARLYBIRD_SCHEDULE = null;

// === HOLY COW WE'RE HOSTING INVITATIONAL — Stratford 4/13/2026 ===
export const HOLYCOW_BOYS = [
  {e:'100 Meter Dash',a:['Draven Dums','Colton Long','Max Losiewicz','Erik Paul','Landon Preuss','Tosh Satterwhite','Jaden Thao'],seed:['13.53','12.11','13.15','13.02','13.39','13.02','13.42']},
  {e:'200 Meter Dash',a:['Axel Brushaber','Draven Dums','Erik Paul','Landon Preuss','Tosh Satterwhite','Jaden Thao','Levi Zulegar'],seed:['26.05','27.97','27.26','27.41','28.03','28.21','25.04']},
  {e:'400 Meter Dash',a:['Sawyer Hoops','Ethan Jacobsen','Tristan Newberry','Peyton Reid','Jasper Stokes'],seed:['55.02','58.05','58.05','58.05','1:05.64']},
  {e:'800 Meter Run',a:['Emmanuel Espinoza','Nevyn Gripentrog','Tristan Newberry','Judah Wipf'],seed:['2:30.26','2:25.85','2:50.32','2:18.67']},
  {e:'1600 Meter Run',a:['Emmanuel Espinoza','Nevyn Gripentrog','Angus Hamland','Evan Pagel'],seed:['5:56.73','5:48.73','5:14.19','5:23.05']},
  {e:'3200 Meter Run',a:['Angus Hamland'],seed:['11:00.00']},
  {e:'110 Meter Hurdles',a:['Parker Judnic'],seed:['20.30']},
  {e:'4x100 Meter Relay',a:['Ryker Hallam','Colton Long','Axel Brushaber','Levi Zulegar','Jordon Lavin','Landon Preuss','Draven Dums','Parker Judnic','Tosh Satterwhite','Max Losiewicz'],n:'2 relay entries'},
  {e:'4x200 Meter Relay',a:['Levi Zulegar','Peyton Reid','Axel Brushaber','Ethan Jacobsen','Sawyer Hoops']},
  {e:'4x400 Meter Relay',a:['Sawyer Hoops','Ethan Jacobsen','Peyton Reid','Judah Wipf','Angus Hamland']},
  {e:'4x800 Meter Relay',a:['Evan Pagel','Nevyn Gripentrog','Peyton Reid','Angus Hamland','Emmanuel Espinoza']},
  {e:'High Jump',a:['Erik Paul'],seed:['5-0']},
  {e:'Long Jump',a:['Emmanuel Espinoza','Ryker Hallam','Tristan Newberry','Jasper Stokes'],seed:['10-4.5','10-4.5','10-4.5','14-1']},
  {e:'Triple Jump',a:['Axel Brushaber','Erik Paul'],seed:['38-4.5','31-3.5']},
  {e:'Pole Vault',a:['Bentley Cooley','Xander Cynor','Jordon Lavin','Max Losiewicz'],seed:['8-6','6-0','12-6','10-0']},
  {e:'Discus',a:['Reuben Barnhart','Johnathon Bartnick','Christopher Dunn','Parker Fogo','Paxton Hamland','Logan Langdon','Logan Schmidt'],seed:['65-9','90-8','85-11','76-3','47-7','125-10','68-8']},
  {e:'Shot Put',a:['Reuben Barnhart','Johnathon Bartnick','Christopher Dunn','Parker Fogo','Paxton Hamland','Logan Langdon','Logan Schmidt'],seed:['28-1','34-2','29-3.5','31-11','23-8','33-6.5','24-6']},
];
export const HOLYCOW_GIRLS = [
  {e:'100 Meter Dash',a:['Jordyn Grant','Alessia Salamin','Rivalee Stokes','Lucy Ulrich'],seed:['13.84','14.51','13.37','15.27']},
  {e:'200 Meter Dash',a:['Taylor Klingbeil','Aliyah Pilgrim','Alexis Zuleger'],seed:['31.50','28.39','29.81']},
  {e:'400 Meter Dash',a:['Taylor Klingbeil','Aliyah Pilgrim','Raylin Rothmeier'],seed:['1:11.00','1:03.79','1:11.00']},
  {e:'800 Meter Run',a:['Autumn Cooley','Melanie Richter'],seed:['2:40.00','2:45.00']},
  {e:'1600 Meter Run',a:['Willow Dassow','Lindsay Kahn','Melanie Richter'],seed:['6:15.40','5:39.86','6:04.40']},
  {e:'3200 Meter Run',a:['Lindsay Kahn'],seed:['12:28.85']},
  {e:'100 Meter Hurdles',a:['Cora Semrau'],seed:['19.35']},
  {e:'300 Meter Hurdles',a:['Cora Semrau'],seed:['57.88']},
  {e:'4x100 Meter Relay',a:['Ellie Eckert','Lucy Ulrich','Jordyn Grant','Rivalee Stokes','Alexis Zuleger']},
  {e:'4x200 Meter Relay',a:['Ellie Eckert','Cora Semrau','Alexis Zuleger','Jordyn Grant','Taylor Klingbeil']},
  {e:'4x800 Meter Relay',a:['Autumn Cooley','Melanie Richter','Willow Dassow','Lindsay Kahn','Lucy Ulrich']},
  {e:'High Jump',a:['Taylor Klingbeil'],seed:['4-0']},
  {e:'Long Jump',a:['Alessia Salamin'],seed:['10-10.5']},
  {e:'Triple Jump',a:['Jordyn Grant'],seed:['32-8.5']},
  {e:'Pole Vault',a:['Avery Losiewicz'],seed:['10-0']},
  {e:'Discus',a:['Sada Carstensen','Savannah Hebert','Mya Matthias','Chloe Pipkorn','Rivalee Stokes','Naomi Thomas'],seed:['77-2','63-2','64-0','39-0','129-10','53-3']},
  {e:'Shot Put',a:['Sada Carstensen','Savannah Hebert','Mya Matthias','Chloe Pipkorn','Rivalee Stokes','Naomi Thomas'],seed:['29-7','24-3','19-10','20-11.5','32-2','24-7.75']},
];

export const HOLYCOW_NOTES = [
  {n:'Angus Hamland',g:'B',ev:'4x800 Relay (9:37.67), 1600M (5:27), 3200M (11:00)',note:'Strong distance base. Manage energy across three events\u2014prioritize relay handoff consistency and pacing discipline on 1600M.'},
  {n:'Axel Brushaber',g:'B',ev:'4x200 Relay, 4x100 Relay, 200M (26.5), Triple Jump',note:'Versatile sprinter and jumper. Keep baton exchanges crisp in relays; use power from relays to fuel TJ approach.'},
  {n:'Bentley Cooley',g:'B',ev:'Pole Vault (9\')',note:'Solid seed. Focus on consistent plant and drive phase\u2014smooth rhythm through the approach.'},
  {n:'Blake Thorson',g:'B',ev:'Shot Put (35\'3"), Discus (63\'6")',note:'Dual thrower. Lock in mechanics for each event\u2014Shot Put: strong drive off leg; Discus: emphasis on rotation consistency.'},
  {n:'Chris Dunn',g:'B',ev:'Shot Put (29\'3.5"), Discus (80\'1")',note:'Distance thrower in Discus. Shot Put is secondary\u2014keep both events clean and controlled, minimize adjustments between them.'},
  {n:'Colton Long',g:'B',ev:'100M (12.16), 4x100 Relay',note:'Quick legs. Explosive start in individual; relay: crisp handoff and smooth acceleration on anchor leg.'},
  {n:'Draven Dums',g:'B',ev:'100M (13.53), 4x100 Relay, 200M (27.97)',note:'Triple threat in sprints. Pace 100M conservatively, build into 200M; relay: clean exchanges and focus on your leg.'},
  {n:'Eric Paul',g:'B',ev:'100M (13.02), 200M (27.26), Triple Jump, High Jump (4\')',note:'Versatile multi-event athlete. Manage four events\u2014prioritize 100M and 200M momentum for HJ approach; TJ: patience and rhythm.'},
  {n:'Ethan Jacobson',g:'B',ev:'4x200 Relay (1:48.07), 400M (58.05), 4x400 Relay',note:'Workhorse in middle distance. Relay: smooth baton work; 400M: run controlled, save finishing kick for anchor leg duty.'},
  {n:'Evan Pagel',g:'B',ev:'4x800 Relay, 1600M (5:45)',note:'Distance pack. Pace relay well\u2014positive split on your leg\u2014then rest briefly before 1600M push.'},
  {n:'Jaden Thao',g:'B',ev:'100M (13.42), 200M (27.03)',note:'Sprinter. Drive hard off blocks in 100M; bring that explosiveness into 200M curve work.'},
  {n:'Jasper Stokes',g:'B',ev:'400M (1:07), Long Jump',note:'Two events, clean slate. 400M\u2014go out controlled through 200M and kick hard. Long Jump\u2014carry that 400M leg drive into an aggressive approach. Compete fearless.'},
  {n:'Jonathon Bartnik',g:'B',ev:'Shot Put (35\'10.75"), Discus (90\'8")',note:'Top thrower distance. Both events strong\u2014Shot Put: explosive power; Discus: nail the spin and follow-through.'},
  {n:'Jordy Lavin',g:'B',ev:'Pole Vault (12\'6")',note:'Elite vaulter. Smooth approach, aggressive plant\u2014trust your speed and drive hard on takeoff.'},
  {n:'Judah Wipf',g:'B',ev:'800M (2:15), 4x400 Relay (3:54.95)',note:'Mid-distance anchor. 800M: strong first 400, kick hard final 200M; relay: confident handoff and powerful close.'},
  {n:'Landon Preuss',g:'B',ev:'100M (13.39), 4x100 Relay, 200M (27.41)',note:'Relay contributor and sprinter. Keep legs fresh for relay exchanges; bring speed from team effort into 200M.'},
  {n:'Levi Zuleger',g:'B',ev:'4x200 Relay, 4x100 Relay (50.28), 200M (25.3)',note:'Quick sprinter. 200M seed is solid\u2014sharp baton work in relays translates to smooth curve running.'},
  {n:'Logan Langdon',g:'B',ev:'Shot Put (38\'4.75"), Discus (125\'10")',note:'Your numbers lead the boys throws. 125\'10" discus and 38\'4" shot\u2014stay loose, trust your spin, and let distance come. You don\'t need to press; technique wins.'},
  {n:'Logan Schmidt',g:'B',ev:'Shot Put (26\'0.75"), Discus (68\'8")',note:'Developing thrower. Shot Put: tight technique and extension; Discus: controlled rotation.'},
  {n:'Manny Espinoza',g:'B',ev:'1600M (6:02), 800M (2:30.26), Long Jump',note:'Multi-event athlete. 1600M\u2014run smart; 800M\u2014fast first lap; Long Jump\u2014use leg power from running.'},
  {n:'Max Losiewicz',g:'B',ev:'100M (13.15), Pole Vault (11\')',note:'Sprinter-vaulter. Speed from 100M helps approach on vault; aggressive plant and drive.'},
  {n:'Nevyn Gripentrog',g:'B',ev:'4x800 Relay, 1600M (5:56), 800M (2:32)',note:'Distance engine. Relay\u2014smooth pace; 800M\u2014fast opener, kick final 200M; manage consecutive events.'},
  {n:'Parker Fogo',g:'B',ev:'Shot Put (31\'11"), Discus (76\'3")',note:'Solid dual thrower. Shot Put first for momentum; Discus: controlled spin and release\u2014build off Shot Put focus.'},
  {n:'Parker Judnic',g:'B',ev:'110m Hurdles (20.30), 4x100 Relay',note:'Hurdler and relay leg. Clear hurdles crisply; relay: smooth baton exchange and aggressive leg.'},
  {n:'Peyton Ried',g:'B',ev:'4x800 Relay, 4x200 Relay, 400M (58.50), 4x400 Relay',note:'Relay workhorse across three teams. Pace relays conservatively\u2014smooth handoffs; 400M controlled effort.'},
  {n:'Reuben Barnhart',g:'B',ev:'Shot Put (28\'1"), Discus (65\'9")',note:'Developing dual thrower. Technical consistency key\u2014Shot Put compact form; Discus steady rhythm.'},
  {n:'Ryker Hallam',g:'B',ev:'4x100 Relay, Long Jump',note:'Relay sprinter with jump ability. Relay: crisp baton work; Long Jump\u2014carry relay momentum into approach.'},
  {n:'Sawyer Hoops',g:'B',ev:'400M (55.60), 4x400 Relay',note:'Strong 400M runner. First 200M controlled, accelerate final 200M; relay anchor\u2014confident finish.'},
  {n:'Tosh Satterwhite',g:'B',ev:'100M (13.02), 4x100 Relay (53.97), 200M (27.00)',note:'Speedy sprinter. Explosive starts; relay: sharp exchanges; 200M shows potential\u2014drive the curve.'},
  {n:'Tristan Newberry',g:'B',ev:'400M (1:10), 800M (2:40), Long Jump',note:'Mid-distance multi-event. 400M\u2014even pacing; 800M\u2014strong finish; Long Jump\u2014use running leg drive.'},
  {n:'Xander Cynor',g:'B',ev:'Pole Vault (6\')',note:'Vault development. Focus on mechanics and consistency\u2014smooth plant, aggressive drive through top.'},
  {n:'Alessia Salamin',g:'G',ev:'100M (14.51), Long Jump',note:'Sprinter-jumper. 100M drives leg power; Long Jump uses that explosiveness\u2014focus on approach rhythm.'},
  {n:'Alexis Zuleger',g:'G',ev:'4x200 Relay, 200M (32.43)',note:'Relay contributor. Clean handoffs; bring relay focus into 200M\u2014smooth curve and controlled finish.'},
  {n:'Aliyah Pilgrim',g:'G',ev:'400M (1:05), 200M (29.7)',note:'Mid-sprinter. 400M\u2014conservative first 200M, kick final stretch; 200M energy management key.'},
  {n:'Autumn Cooley',g:'G',ev:'4x800 Relay, 800M (2:40)',note:'Distance runner. Relay\u2014consistent pace; 800M\u2014fast opener, strong kick final 200M.'},
  {n:'Avery Losiewicz',g:'G',ev:'Pole Vault (8\')',note:'Vaulter with steady seed. Confident approach and plant\u2014aggressive drive for vertical clearance.'},
  {n:'Chloe Pipkorn',g:'G',ev:'Shot Put (20\'11.5"), Discus (39\'11")',note:'Dual thrower. Shot Put\u2014tight extension and drive; Discus\u2014controlled rotation and follow-through.'},
  {n:'Cora Semrau',g:'G',ev:'100m Hurdles, 4x200 Relay, 300m Hurdles (59.00)',note:'Hurdler and relay runner. Clear hurdles crisply; 300m Hurdles\u2014aggressive rhythm between flights; relay exchanges smooth.'},
  {n:'Ellie Eckert',g:'G',ev:'4x200 Relay, 4x100 Relay',note:'Relay specialist. Crisp baton work critical in both events\u2014smooth transitions and confident leg execution.'},
  {n:'Jordyn Grant',g:'G',ev:'100M (13.84), 4x200 Relay (2:09.50), 4x100 Relay, Triple Jump',note:'Versatile sprinter-jumper. Explosive starts; relay\u2014clean exchanges; Triple Jump\u2014aggressive approach and rhythm.'},
  {n:'Lindsay Kahn',g:'G',ev:'4x800 Relay (11:12), 1600M (5:48), 3200M (12:50)',note:'Distance engine. Relay\u2014even splits; 1600M and 3200M\u2014manage energy across events\u2014strong pacing discipline.'},
  {n:'Lucy Ulrich',g:'G',ev:'100M (15.27), 4x100 Relay',note:'Relay contributor. Smooth baton exchange; 100M\u2014explosive drive off blocks.'},
  {n:'Melanie Richter',g:'G',ev:'4x800 Relay, 1600M (6:04), 800M (2:45)',note:'Distance runner. Relay\u2014consistent pace; 800M\u2014fast first lap, kick hard; manage back-to-back events.'},
  {n:'Mya Matthias',g:'G',ev:'Shot Put (21\'0.5"), Discus (64\'11")',note:'Dual thrower. Shot Put compact power; Discus\u2014controlled rotation and solid follow-through technique.'},
  {n:'Naomi Thomas',g:'G',ev:'Shot Put (24\'6.5"), Discus (53\'3")',note:'Developing dual thrower. Shot Put\u2014tight mechanics and extension; Discus\u2014smooth rhythm and release.'},
  {n:'Raylin Rothmeier',g:'G',ev:'400M (1:11)',note:'Mid-distance runner. Even pacing through 200M, strong kick final stretch\u2014control and confidence.'},
  {n:'Rivalee Stokes',g:'G',ev:'100M (13.64), 4x100 Relay (58.81), Shot Put (32\'2"), Discus (129\'10")',note:'You hold the meet record in discus\u2014defend it. That 129\'10" is dominant and the shot put backs it up. Sprint and relay legs keep your legs fast. Four events is a big day; manage energy, execute throws, own the ring.'},
  {n:'Sada Carstensen',g:'G',ev:'Shot Put (29\'7"), Discus (77\'2")',note:'Solid dual thrower. Shot Put\u2014aggressive drive; Discus distance seed\u2014emphasize technique and rotation control.'},
  {n:'Savannah Hebert',g:'G',ev:'Shot Put (24\'3"), Discus (63\'2")',note:'Developing dual thrower. Shot Put technique focus; Discus\u2014controlled spin and solid release.'},
  {n:'Taylor Klingbeil',g:'G',ev:'400M (1:11), 200M (31.5), High Jump',note:'Multi-event athlete. 400M\u2014controlled pace; 200M\u2014legs fresh; High Jump\u2014use power and approach rhythm.'},
  {n:'Willow Dassow',g:'G',ev:'4x800 Relay, 1600M (6:15)',note:'Distance runner. Relay\u2014smooth, even-paced leg; 1600M\u2014strong kick final 400M.'},
];
